package org.yawlfoundation.yawl.editor.core.repository;

import org.yawlfoundation.yawl.elements.*;
import org.yawlfoundation.yawl.exceptions.YSyntaxException;
import org.yawlfoundation.yawl.unmarshal.YMarshal;
import org.yawlfoundation.yawl.unmarshal.YMetaData;
import org.yawlfoundation.yawl.util.XNode;
import org.yawlfoundation.yawl.util.XNodeParser;

import java.util.List;

/**
 * @author Michael Adams
 * @date 6/08/13
 */
public abstract class DecompositionRepoMap extends RepoMap {

    private XNode shellSpecification;
    private XNodeParser parser;

    protected DecompositionRepoMap() { }

    protected DecompositionRepoMap(String path) {
        super(path);
    }

    /**
     * Adds a task decomposition to the repository
     * @param name a reference name for the task decomposition
     * @param description a description of it
     * @param decomposition the task decomposition to add
     * @return whether the add was successful
     */
    protected String add(String name, String description, YDecomposition decomposition) {
        if (! anyAreNull(name, description, decomposition)) {
            RepoRecord record = addRecord(
                    new RepoRecord(name, description, toXML(decomposition)));
            if (record != null) return record.getName();
        }
        return null;
    }


    /**
     * Gets a task decomposition from the repository
     * @param name a reference name for the task decomposition
     * @return the referenced task decomposition, or null if not found
     */
    public YDecomposition get(String name) throws YSyntaxException {
        RepoRecord record = getRecord(name);
        return record != null ? parse(record.getValue()) : null;
    }


    /**
     * Removes a task decomposition from the repository
     * @param name a reference name for the task decomposition
     * @return whether the removal was successful
     */
    public YDecomposition remove(String name) {
        RepoRecord record = removeRecord(name);
        if (record != null) {
            try {
                return parse(record.getValue());
            }
            catch (YSyntaxException yse) {
                // fall through to null
            }
        }
        return null;
    }


    /**
     * Gets a sorted list of descriptors for all stored task decompositions
     * @return A sorted list of RepoDescriptors (String pairs - name, description)
     */
    public List<RepoDescriptor> getDescriptors() {
        return super.getDescriptors();
    }


    // writes a task decomposition to xml
    // since a specification adds some xml to that generated by a decomposition, we
    // have to replicate it here
    protected abstract String toXML(YDecomposition decomposition);


    protected abstract void addXsiAttribute(XNode decompositionNode);


    /**
     * Creates a task decomposition from its XML description
     * @param xml the XML to parse
     * @return the populated task decomposition
     */
    protected YDecomposition parse(String xml) throws YSyntaxException {
        if (xml == null) return null;
        if (parser == null) parser = new XNodeParser();
        XNode decompositionNode = parser.parse(xml);
        return decompositionNode == null ? null :
                unmarshalDecomposition(decompositionNode);
    }


    private XNode createShellSpecification() {
        try {
            YSpecification s = new YSpecification("repoShell");
            s.setMetaData(new YMetaData());
            s.setSchema("<xs:schema xmlns:xs=\"http://www.w3.org/2001/XMLSchema\"/>");
            YNet root = new YNet("rootNet", s);
            root.setInputCondition(new YInputCondition("in", root));
            root.setOutputCondition(new YOutputCondition("out", root));
            s.setRootNet(root);

            String repoShellXML = YMarshal.marshal(s);
            return new XNodeParser().parse(repoShellXML);
        }
        catch (YSyntaxException yse) {
            return null;
        }
    }


    private YDecomposition unmarshalDecomposition(XNode decompositionNode)
            throws YSyntaxException {
        if (shellSpecification == null) shellSpecification = createShellSpecification();
        XNode specNode = shellSpecification.getChild("specification");
        addXsiAttribute(decompositionNode);   // for task or net decomposition
        specNode.addChild(decompositionNode);
        YSpecification specification = YMarshal.unmarshalSpecifications(
                shellSpecification.toString(true), false).get(0);
        specNode.removeChild(decompositionNode);
        for (YDecomposition decomposition : specification.getDecompositions()) {
            if (! decomposition.getID().equals("rootNet")) {
                return decomposition;
            }
        }
        return null;
    }

}
