//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.05.19 at 04:56:47 PM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.yawlfoundation.org/sb/soundInfo")
package org.yawlfoundation.sb.soundinfo;
