//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.06.02 at 01:01:41 PM EST 
//


package org.yawlfoundation.sb.callsheetinfo;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.yawlfoundation.sb.callsheetinfo package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _FillOutCallSheet_QNAME = new QName("http://www.yawlfoundation.org/sb/callSheetInfo", "Fill_Out_CallSheet");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.yawlfoundation.sb.callsheetinfo
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SingleCastInfoCallType }
     * 
     */
    public SingleCastInfoCallType createSingleCastInfoCallType() {
        return new SingleCastInfoCallType();
    }

    /**
     * Create an instance of {@link SingleEntryType }
     * 
     */
    public SingleEntryType createSingleEntryType() {
        return new SingleEntryType();
    }

    /**
     * Create an instance of {@link CateringType }
     * 
     */
    public CateringType createCateringType() {
        return new CateringType();
    }

    /**
     * Create an instance of {@link GeneralInfoType }
     * 
     */
    public GeneralInfoType createGeneralInfoType() {
        return new GeneralInfoType();
    }

    /**
     * Create an instance of {@link LocationContactInfoType }
     * 
     */
    public LocationContactInfoType createLocationContactInfoType() {
        return new LocationContactInfoType();
    }

    /**
     * Create an instance of {@link CallSheetInputInfoType }
     * 
     */
    public CallSheetInputInfoType createCallSheetInputInfoType() {
        return new CallSheetInputInfoType();
    }

    /**
     * Create an instance of {@link SingleCrewContactType }
     * 
     */
    public SingleCrewContactType createSingleCrewContactType() {
        return new SingleCrewContactType();
    }

    /**
     * Create an instance of {@link SingleMealType }
     * 
     */
    public SingleMealType createSingleMealType() {
        return new SingleMealType();
    }

    /**
     * Create an instance of {@link SingleCallTimeType }
     * 
     */
    public SingleCallTimeType createSingleCallTimeType() {
        return new SingleCallTimeType();
    }

    /**
     * Create an instance of {@link SingleLocationContactInfoType }
     * 
     */
    public SingleLocationContactInfoType createSingleLocationContactInfoType() {
        return new SingleLocationContactInfoType();
    }

    /**
     * Create an instance of {@link MovementOrdersType }
     * 
     */
    public MovementOrdersType createMovementOrdersType() {
        return new MovementOrdersType();
    }

    /**
     * Create an instance of {@link SingleSceneShootingScheduleType }
     * 
     */
    public SingleSceneShootingScheduleType createSingleSceneShootingScheduleType() {
        return new SingleSceneShootingScheduleType();
    }

    /**
     * Create an instance of {@link SetInfoType }
     * 
     */
    public SetInfoType createSetInfoType() {
        return new SetInfoType();
    }

    /**
     * Create an instance of {@link FillOutCallSheetType }
     * 
     */
    public FillOutCallSheetType createFillOutCallSheetType() {
        return new FillOutCallSheetType();
    }

    /**
     * Create an instance of {@link CrewContactsType }
     * 
     */
    public CrewContactsType createCrewContactsType() {
        return new CrewContactsType();
    }

    /**
     * Create an instance of {@link SingleSceneShootingType }
     * 
     */
    public SingleSceneShootingType createSingleSceneShootingType() {
        return new SingleSceneShootingType();
    }

    /**
     * Create an instance of {@link CallSheetOutputInfoType }
     * 
     */
    public CallSheetOutputInfoType createCallSheetOutputInfoType() {
        return new CallSheetOutputInfoType();
    }

    /**
     * Create an instance of {@link SceneNOsType }
     * 
     */
    public SceneNOsType createSceneNOsType() {
        return new SceneNOsType();
    }

    /**
     * Create an instance of {@link SceneShootingScheduleType }
     * 
     */
    public SceneShootingScheduleType createSceneShootingScheduleType() {
        return new SceneShootingScheduleType();
    }

    /**
     * Create an instance of {@link CallTimesType }
     * 
     */
    public CallTimesType createCallTimesType() {
        return new CallTimesType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FillOutCallSheetType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.yawlfoundation.org/sb/callSheetInfo", name = "Fill_Out_CallSheet")
    public JAXBElement<FillOutCallSheetType> createFillOutCallSheet(FillOutCallSheetType value) {
        return new JAXBElement<FillOutCallSheetType>(_FillOutCallSheet_QNAME, FillOutCallSheetType.class, null, value);
    }

}
