//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.06.02 at 01:01:41 PM EST 
//


package org.yawlfoundation.sb.callsheetinfo;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for singleSceneShootingScheduleType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="singleSceneShootingScheduleType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="activity" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="singleSceneShooting" type="{http://www.yawlfoundation.org/sb/callSheetInfo}singleSceneShootingType" maxOccurs="unbounded"/>
 *         &lt;element name="endOfDayRemarks" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "singleSceneShootingScheduleType", propOrder = {
    "activity",
    "singleSceneShooting",
    "endOfDayRemarks"
})
public class SingleSceneShootingScheduleType {

    protected List<String> activity;
    @XmlElement(required = true)
    protected List<SingleSceneShootingType> singleSceneShooting;
    @XmlElement(required = true)
    protected String endOfDayRemarks;

    /**
     * Gets the value of the activity property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the activity property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getActivity().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getActivity() {
        if (activity == null) {
            activity = new ArrayList<String>();
        }
        return this.activity;
    }

    /**
     * Gets the value of the singleSceneShooting property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the singleSceneShooting property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSingleSceneShooting().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SingleSceneShootingType }
     * 
     * 
     */
    public List<SingleSceneShootingType> getSingleSceneShooting() {
        if (singleSceneShooting == null) {
            singleSceneShooting = new ArrayList<SingleSceneShootingType>();
        }
        return this.singleSceneShooting;
    }

    /**
     * Gets the value of the endOfDayRemarks property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEndOfDayRemarks() {
        return endOfDayRemarks;
    }

    /**
     * Sets the value of the endOfDayRemarks property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEndOfDayRemarks(String value) {
        this.endOfDayRemarks = value;
    }

}
