//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.05.19 at 10:36:31 AM EST 
//


package org.yawlfoundation.sb.continuityinfo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Fill_Out_Continuity_ReportType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Fill_Out_Continuity_ReportType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="generalInfo" type="{http://www.yawlfoundation.org/sb/continuityInfo}generalInfoType"/>
 *         &lt;element name="producer" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="director" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="directorOfPhotography" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="editor" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="continuity" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="continuityInfo" type="{http://www.yawlfoundation.org/sb/continuityInfo}continuityInfoType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Fill_Out_Continuity_ReportType", propOrder = {
    "generalInfo",
    "producer",
    "director",
    "directorOfPhotography",
    "editor",
    "continuity",
    "continuityInfo"
})
public class FillOutContinuityReportType {

    @XmlElement(required = true)
    protected GeneralInfoType generalInfo;
    @XmlElement(required = true)
    protected String producer;
    @XmlElement(required = true)
    protected String director;
    @XmlElement(required = true)
    protected String directorOfPhotography;
    @XmlElement(required = true)
    protected String editor;
    @XmlElement(required = true)
    protected String continuity;
    @XmlElement(required = true)
    protected ContinuityInfoType continuityInfo;

    /**
     * Gets the value of the generalInfo property.
     * 
     * @return
     *     possible object is
     *     {@link GeneralInfoType }
     *     
     */
    public GeneralInfoType getGeneralInfo() {
        return generalInfo;
    }

    /**
     * Sets the value of the generalInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link GeneralInfoType }
     *     
     */
    public void setGeneralInfo(GeneralInfoType value) {
        this.generalInfo = value;
    }

    /**
     * Gets the value of the producer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProducer() {
        return producer;
    }

    /**
     * Sets the value of the producer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProducer(String value) {
        this.producer = value;
    }

    /**
     * Gets the value of the director property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDirector() {
        return director;
    }

    /**
     * Sets the value of the director property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDirector(String value) {
        this.director = value;
    }

    /**
     * Gets the value of the directorOfPhotography property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDirectorOfPhotography() {
        return directorOfPhotography;
    }

    /**
     * Sets the value of the directorOfPhotography property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDirectorOfPhotography(String value) {
        this.directorOfPhotography = value;
    }

    /**
     * Gets the value of the editor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEditor() {
        return editor;
    }

    /**
     * Sets the value of the editor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEditor(String value) {
        this.editor = value;
    }

    /**
     * Gets the value of the continuity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContinuity() {
        return continuity;
    }

    /**
     * Sets the value of the continuity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContinuity(String value) {
        this.continuity = value;
    }

    /**
     * Gets the value of the continuityInfo property.
     * 
     * @return
     *     possible object is
     *     {@link ContinuityInfoType }
     *     
     */
    public ContinuityInfoType getContinuityInfo() {
        return continuityInfo;
    }

    /**
     * Sets the value of the continuityInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContinuityInfoType }
     *     
     */
    public void setContinuityInfo(ContinuityInfoType value) {
        this.continuityInfo = value;
    }

}
