//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-20060407-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.04.10 at 05:56:34 PM EDT 
//


package au.edu.qut.yawl.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DecompositionFactsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DecompositionFactsType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.citi.qut.edu.au/yawl}DecompositionType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.citi.qut.edu.au/yawl}NameType" minOccurs="0"/>
 *         &lt;element name="documentation" type="{http://www.citi.qut.edu.au/yawl}DocumentationType" minOccurs="0"/>
 *         &lt;element name="inputParam" type="{http://www.citi.qut.edu.au/yawl}InputParameterFactsType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="outputParam" type="{http://www.citi.qut.edu.au/yawl}OutputParameterFactsType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DecompositionFactsType", propOrder = {
    "name",
    "documentation",
    "inputParam",
    "outputParam"
})
public abstract class DecompositionFactsType
    extends DecompositionType
{

    @XmlElement(namespace = "http://www.citi.qut.edu.au/yawl")
    protected String name;
    @XmlElement(namespace = "http://www.citi.qut.edu.au/yawl")
    protected String documentation;
    @XmlElement(namespace = "http://www.citi.qut.edu.au/yawl", required = true)
    protected List<InputParameterFactsType> inputParam;
    @XmlElement(namespace = "http://www.citi.qut.edu.au/yawl", required = true)
    protected List<OutputParameterFactsType> outputParam;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the documentation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentation() {
        return documentation;
    }

    /**
     * Sets the value of the documentation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentation(String value) {
        this.documentation = value;
    }

    /**
     * Gets the value of the inputParam property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the inputParam property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInputParam().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InputParameterFactsType }
     * 
     * 
     */
    public List<InputParameterFactsType> getInputParam() {
        if (inputParam == null) {
            inputParam = new ArrayList<InputParameterFactsType>();
        }
        return this.inputParam;
    }

    /**
     * Gets the value of the outputParam property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the outputParam property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOutputParam().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OutputParameterFactsType }
     * 
     * 
     */
    public List<OutputParameterFactsType> getOutputParam() {
        if (outputParam == null) {
            outputParam = new ArrayList<OutputParameterFactsType>();
        }
        return this.outputParam;
    }

}
