//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-20060407-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.04.10 at 05:56:34 PM EDT 
//


package au.edu.qut.yawl.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import au.edu.qut.yawl.jaxb.MultipleInstanceExternalTaskFactsType.MiDataInput;
import au.edu.qut.yawl.jaxb.MultipleInstanceExternalTaskFactsType.MiDataOutput;


/**
 * <p>Java class for MultipleInstanceExternalTaskFactsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MultipleInstanceExternalTaskFactsType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.citi.qut.edu.au/yawl}ExternalTaskFactsType">
 *       &lt;sequence>
 *         &lt;element name="minimum" type="{http://www.citi.qut.edu.au/yawl}XQueryType"/>
 *         &lt;element name="maximum" type="{http://www.citi.qut.edu.au/yawl}XQueryType"/>
 *         &lt;element name="threshold" type="{http://www.citi.qut.edu.au/yawl}XQueryType"/>
 *         &lt;element name="creationMode" type="{http://www.citi.qut.edu.au/yawl}CreationModeType"/>
 *         &lt;element name="miDataInput">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="expression" type="{http://www.citi.qut.edu.au/yawl}ExpressionType"/>
 *                   &lt;element name="splittingExpression" type="{http://www.citi.qut.edu.au/yawl}ExpressionType"/>
 *                   &lt;element name="formalInputParam" type="{http://www.citi.qut.edu.au/yawl}VariableNameType"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="miDataOutput" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="formalOutputExpression" type="{http://www.citi.qut.edu.au/yawl}ExpressionType"/>
 *                   &lt;element name="outputJoiningExpression" type="{http://www.citi.qut.edu.au/yawl}ExpressionType"/>
 *                   &lt;element name="resultAppliedToLocalVariable" type="{http://www.citi.qut.edu.au/yawl}VariableNameType"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MultipleInstanceExternalTaskFactsType", propOrder = {
    "minimum",
    "maximum",
    "threshold",
    "creationMode",
    "miDataInput",
    "miDataOutput"
})
public class MultipleInstanceExternalTaskFactsType
    extends ExternalTaskFactsType
{

    @XmlElement(namespace = "http://www.citi.qut.edu.au/yawl", required = true)
    protected String minimum;
    @XmlElement(namespace = "http://www.citi.qut.edu.au/yawl", required = true)
    protected String maximum;
    @XmlElement(namespace = "http://www.citi.qut.edu.au/yawl", required = true)
    protected String threshold;
    @XmlElement(namespace = "http://www.citi.qut.edu.au/yawl", required = true)
    protected CreationModeType creationMode;
    @XmlElement(namespace = "http://www.citi.qut.edu.au/yawl", required = true)
    protected MiDataInput miDataInput;
    @XmlElement(namespace = "http://www.citi.qut.edu.au/yawl")
    protected MiDataOutput miDataOutput;

    /**
     * Gets the value of the minimum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMinimum() {
        return minimum;
    }

    /**
     * Sets the value of the minimum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMinimum(String value) {
        this.minimum = value;
    }

    /**
     * Gets the value of the maximum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaximum() {
        return maximum;
    }

    /**
     * Sets the value of the maximum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaximum(String value) {
        this.maximum = value;
    }

    /**
     * Gets the value of the threshold property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getThreshold() {
        return threshold;
    }

    /**
     * Sets the value of the threshold property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setThreshold(String value) {
        this.threshold = value;
    }

    /**
     * Gets the value of the creationMode property.
     * 
     * @return
     *     possible object is
     *     {@link CreationModeType }
     *     
     */
    public CreationModeType getCreationMode() {
        return creationMode;
    }

    /**
     * Sets the value of the creationMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link CreationModeType }
     *     
     */
    public void setCreationMode(CreationModeType value) {
        this.creationMode = value;
    }

    /**
     * Gets the value of the miDataInput property.
     * 
     * @return
     *     possible object is
     *     {@link MiDataInput }
     *     
     */
    public MiDataInput getMiDataInput() {
        return miDataInput;
    }

    /**
     * Sets the value of the miDataInput property.
     * 
     * @param value
     *     allowed object is
     *     {@link MiDataInput }
     *     
     */
    public void setMiDataInput(MiDataInput value) {
        this.miDataInput = value;
    }

    /**
     * Gets the value of the miDataOutput property.
     * 
     * @return
     *     possible object is
     *     {@link MiDataOutput }
     *     
     */
    public MiDataOutput getMiDataOutput() {
        return miDataOutput;
    }

    /**
     * Sets the value of the miDataOutput property.
     * 
     * @param value
     *     allowed object is
     *     {@link MiDataOutput }
     *     
     */
    public void setMiDataOutput(MiDataOutput value) {
        this.miDataOutput = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="expression" type="{http://www.citi.qut.edu.au/yawl}ExpressionType"/>
     *         &lt;element name="splittingExpression" type="{http://www.citi.qut.edu.au/yawl}ExpressionType"/>
     *         &lt;element name="formalInputParam" type="{http://www.citi.qut.edu.au/yawl}VariableNameType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "expression",
        "splittingExpression",
        "formalInputParam"
    })
    public static class MiDataInput {

        @XmlElement(namespace = "http://www.citi.qut.edu.au/yawl", required = true)
        protected ExpressionType expression;
        @XmlElement(namespace = "http://www.citi.qut.edu.au/yawl", required = true)
        protected ExpressionType splittingExpression;
        @XmlElement(namespace = "http://www.citi.qut.edu.au/yawl", required = true)
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String formalInputParam;

        /**
         * Gets the value of the expression property.
         * 
         * @return
         *     possible object is
         *     {@link ExpressionType }
         *     
         */
        public ExpressionType getExpression() {
            return expression;
        }

        /**
         * Sets the value of the expression property.
         * 
         * @param value
         *     allowed object is
         *     {@link ExpressionType }
         *     
         */
        public void setExpression(ExpressionType value) {
            this.expression = value;
        }

        /**
         * Gets the value of the splittingExpression property.
         * 
         * @return
         *     possible object is
         *     {@link ExpressionType }
         *     
         */
        public ExpressionType getSplittingExpression() {
            return splittingExpression;
        }

        /**
         * Sets the value of the splittingExpression property.
         * 
         * @param value
         *     allowed object is
         *     {@link ExpressionType }
         *     
         */
        public void setSplittingExpression(ExpressionType value) {
            this.splittingExpression = value;
        }

        /**
         * Gets the value of the formalInputParam property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFormalInputParam() {
            return formalInputParam;
        }

        /**
         * Sets the value of the formalInputParam property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFormalInputParam(String value) {
            this.formalInputParam = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="formalOutputExpression" type="{http://www.citi.qut.edu.au/yawl}ExpressionType"/>
     *         &lt;element name="outputJoiningExpression" type="{http://www.citi.qut.edu.au/yawl}ExpressionType"/>
     *         &lt;element name="resultAppliedToLocalVariable" type="{http://www.citi.qut.edu.au/yawl}VariableNameType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "formalOutputExpression",
        "outputJoiningExpression",
        "resultAppliedToLocalVariable"
    })
    public static class MiDataOutput {

        @XmlElement(namespace = "http://www.citi.qut.edu.au/yawl", required = true)
        protected ExpressionType formalOutputExpression;
        @XmlElement(namespace = "http://www.citi.qut.edu.au/yawl", required = true)
        protected ExpressionType outputJoiningExpression;
        @XmlElement(namespace = "http://www.citi.qut.edu.au/yawl", required = true)
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String resultAppliedToLocalVariable;

        /**
         * Gets the value of the formalOutputExpression property.
         * 
         * @return
         *     possible object is
         *     {@link ExpressionType }
         *     
         */
        public ExpressionType getFormalOutputExpression() {
            return formalOutputExpression;
        }

        /**
         * Sets the value of the formalOutputExpression property.
         * 
         * @param value
         *     allowed object is
         *     {@link ExpressionType }
         *     
         */
        public void setFormalOutputExpression(ExpressionType value) {
            this.formalOutputExpression = value;
        }

        /**
         * Gets the value of the outputJoiningExpression property.
         * 
         * @return
         *     possible object is
         *     {@link ExpressionType }
         *     
         */
        public ExpressionType getOutputJoiningExpression() {
            return outputJoiningExpression;
        }

        /**
         * Sets the value of the outputJoiningExpression property.
         * 
         * @param value
         *     allowed object is
         *     {@link ExpressionType }
         *     
         */
        public void setOutputJoiningExpression(ExpressionType value) {
            this.outputJoiningExpression = value;
        }

        /**
         * Gets the value of the resultAppliedToLocalVariable property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getResultAppliedToLocalVariable() {
            return resultAppliedToLocalVariable;
        }

        /**
         * Sets the value of the resultAppliedToLocalVariable property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setResultAppliedToLocalVariable(String value) {
            this.resultAppliedToLocalVariable = value;
        }

    }

}
