//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-20060407-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.04.10 at 05:56:34 PM EDT 
//


package au.edu.qut.yawl.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;
import au.edu.qut.yawl.jaxb.AddressType.NumAndStreet;
import au.edu.qut.yawl.jaxb.ExternalConfigurationListComplexType.ExternalConfiguration;
import au.edu.qut.yawl.jaxb.MultipleInstanceExternalTaskFactsType.MiDataInput;
import au.edu.qut.yawl.jaxb.MultipleInstanceExternalTaskFactsType.MiDataOutput;
import au.edu.qut.yawl.jaxb.NetFactsType.ProcessControlElements;
import au.edu.qut.yawl.jaxb.SchemaType.Type;
import au.edu.qut.yawl.jaxb.WebServiceGatewayFactsType.YawlService;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the au.edu.qut.yawl.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ExternalConfigurationList_QNAME = new QName("http://www.citi.qut.edu.au/yawl", "externalConfigurationList");
    private final static QName _SpecificationSet_QNAME = new QName("http://www.citi.qut.edu.au/yawl", "specificationSet");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: au.edu.qut.yawl.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MiDataOutput }
     * 
     */
    public MiDataOutput createMultipleInstanceExternalTaskFactsTypeMiDataOutput() {
        return new MiDataOutput();
    }

    /**
     * Create an instance of {@link OutputConditionFactsType }
     * 
     */
    public OutputConditionFactsType createOutputConditionFactsType() {
        return new OutputConditionFactsType();
    }

    /**
     * Create an instance of {@link MetaDataType }
     * 
     */
    public MetaDataType createMetaDataType() {
        return new MetaDataType();
    }

    /**
     * Create an instance of {@link AddressType }
     * 
     */
    public AddressType createAddressType() {
        return new AddressType();
    }

    /**
     * Create an instance of {@link TypeNameType }
     * 
     */
    public TypeNameType createTypeNameType() {
        return new TypeNameType();
    }

    /**
     * Create an instance of {@link NumAndStreet }
     * 
     */
    public NumAndStreet createAddressTypeNumAndStreet() {
        return new NumAndStreet();
    }

    /**
     * Create an instance of {@link NetFactsType }
     * 
     */
    public NetFactsType createNetFactsType() {
        return new NetFactsType();
    }

    /**
     * Create an instance of {@link LocationType }
     * 
     */
    public LocationType createLocationType() {
        return new LocationType();
    }

    /**
     * Create an instance of {@link DirectionType }
     * 
     */
    public DirectionType createDirectionType() {
        return new DirectionType();
    }

    /**
     * Create an instance of {@link SpecificationSetType }
     * 
     */
    public SpecificationSetType createSpecificationSetType() {
        return new SpecificationSetType();
    }

    /**
     * Create an instance of {@link WebServiceGatewayFactsType }
     * 
     */
    public WebServiceGatewayFactsType createWebServiceGatewayFactsType() {
        return new WebServiceGatewayFactsType();
    }

    /**
     * Create an instance of {@link SpecificationType }
     * 
     */
    public SpecificationType createSpecificationType() {
        return new SpecificationType();
    }

    /**
     * Create an instance of {@link ExternalNetElementType }
     * 
     */
    public ExternalNetElementType createExternalNetElementType() {
        return new ExternalNetElementType();
    }

    /**
     * Create an instance of {@link ExternalTaskFactsType }
     * 
     */
    public ExternalTaskFactsType createExternalTaskFactsType() {
        return new ExternalTaskFactsType();
    }

    /**
     * Create an instance of {@link TypeType }
     * 
     */
    public TypeType createTypeType() {
        return new TypeType();
    }

    /**
     * Create an instance of {@link YawlService }
     * 
     */
    public YawlService createWebServiceGatewayFactsTypeYawlService() {
        return new YawlService();
    }

    /**
     * Create an instance of {@link VariableFactsType }
     * 
     */
    public VariableFactsType createVariableFactsType() {
        return new VariableFactsType();
    }

    /**
     * Create an instance of {@link VariableBaseType }
     * 
     */
    public VariableBaseType createVariableBaseType() {
        return new VariableBaseType();
    }

    /**
     * Create an instance of {@link SchemaType }
     * 
     */
    public SchemaType createSchemaType() {
        return new SchemaType();
    }

    /**
     * Create an instance of {@link IndividualOrOrganisationType }
     * 
     */
    public IndividualOrOrganisationType createIndividualOrOrganisationType() {
        return new IndividualOrOrganisationType();
    }

    /**
     * Create an instance of {@link NamespacePrefixType }
     * 
     */
    public NamespacePrefixType createNamespacePrefixType() {
        return new NamespacePrefixType();
    }

    /**
     * Create an instance of {@link ImportType }
     * 
     */
    public ImportType createImportType() {
        return new ImportType();
    }

    /**
     * Create an instance of {@link SpecificationSetFactsType }
     * 
     */
    public SpecificationSetFactsType createSpecificationSetFactsType() {
        return new SpecificationSetFactsType();
    }

    /**
     * Create an instance of {@link CustomSchemaNamespaceMappingFactsType }
     * 
     */
    public CustomSchemaNamespaceMappingFactsType createCustomSchemaNamespaceMappingFactsType() {
        return new CustomSchemaNamespaceMappingFactsType();
    }

    /**
     * Create an instance of {@link OutputParameterFactsType }
     * 
     */
    public OutputParameterFactsType createOutputParameterFactsType() {
        return new OutputParameterFactsType();
    }

    /**
     * Create an instance of {@link VarMappingFactsType }
     * 
     */
    public VarMappingFactsType createVarMappingFactsType() {
        return new VarMappingFactsType();
    }

    /**
     * Create an instance of {@link CreationModeType }
     * 
     */
    public CreationModeType createCreationModeType() {
        return new CreationModeType();
    }

    /**
     * Create an instance of {@link PredicateType }
     * 
     */
    public PredicateType createPredicateType() {
        return new PredicateType();
    }

    /**
     * Create an instance of {@link ProcessControlElements }
     * 
     */
    public ProcessControlElements createNetFactsTypeProcessControlElements() {
        return new ProcessControlElements();
    }

    /**
     * Create an instance of {@link RemovesTokensFromFlowType }
     * 
     */
    public RemovesTokensFromFlowType createRemovesTokensFromFlowType() {
        return new RemovesTokensFromFlowType();
    }

    /**
     * Create an instance of {@link ExternalConfigurationListComplexType }
     * 
     */
    public ExternalConfigurationListComplexType createExternalConfigurationListComplexType() {
        return new ExternalConfigurationListComplexType();
    }

    /**
     * Create an instance of {@link YAWLSpecificationFactsType }
     * 
     */
    public YAWLSpecificationFactsType createYAWLSpecificationFactsType() {
        return new YAWLSpecificationFactsType();
    }

    /**
     * Create an instance of {@link CustomSchemaNamespaceMappingType }
     * 
     */
    public CustomSchemaNamespaceMappingType createCustomSchemaNamespaceMappingType() {
        return new CustomSchemaNamespaceMappingType();
    }

    /**
     * Create an instance of {@link NamespaceURI }
     * 
     */
    public NamespaceURI createNamespaceURI() {
        return new NamespaceURI();
    }

    /**
     * Create an instance of {@link FlowsIntoType }
     * 
     */
    public FlowsIntoType createFlowsIntoType() {
        return new FlowsIntoType();
    }

    /**
     * Create an instance of {@link MultipleInstanceExternalTaskFactsType }
     * 
     */
    public MultipleInstanceExternalTaskFactsType createMultipleInstanceExternalTaskFactsType() {
        return new MultipleInstanceExternalTaskFactsType();
    }

    /**
     * Create an instance of {@link DecompositionType }
     * 
     */
    public DecompositionType createDecompositionType() {
        return new DecompositionType();
    }

    /**
     * Create an instance of {@link ExpressionType }
     * 
     */
    public ExpressionType createExpressionType() {
        return new ExpressionType();
    }

    /**
     * Create an instance of {@link ExternalConfiguration }
     * 
     */
    public ExternalConfiguration createExternalConfigurationListComplexTypeExternalConfiguration() {
        return new ExternalConfiguration();
    }

    /**
     * Create an instance of {@link MiDataInput }
     * 
     */
    public MiDataInput createMultipleInstanceExternalTaskFactsTypeMiDataInput() {
        return new MiDataInput();
    }

    /**
     * Create an instance of {@link VarMappingSetType }
     * 
     */
    public VarMappingSetType createVarMappingSetType() {
        return new VarMappingSetType();
    }

    /**
     * Create an instance of {@link Type }
     * 
     */
    public Type createSchemaTypeType() {
        return new Type();
    }

    /**
     * Create an instance of {@link ControlTypeType }
     * 
     */
    public ControlTypeType createControlTypeType() {
        return new ControlTypeType();
    }

    /**
     * Create an instance of {@link InputParameterFactsType }
     * 
     */
    public InputParameterFactsType createInputParameterFactsType() {
        return new InputParameterFactsType();
    }

    /**
     * Create an instance of {@link ExternalNetElementFactsType }
     * 
     */
    public ExternalNetElementFactsType createExternalNetElementFactsType() {
        return new ExternalNetElementFactsType();
    }

    /**
     * Create an instance of {@link ExternalConditionFactsType }
     * 
     */
    public ExternalConditionFactsType createExternalConditionFactsType() {
        return new ExternalConditionFactsType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExternalConfigurationListComplexType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.citi.qut.edu.au/yawl", name = "externalConfigurationList")
    public JAXBElement<ExternalConfigurationListComplexType> createExternalConfigurationList(ExternalConfigurationListComplexType value) {
        return new JAXBElement<ExternalConfigurationListComplexType>(_ExternalConfigurationList_QNAME, ExternalConfigurationListComplexType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SpecificationSetFactsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.citi.qut.edu.au/yawl", name = "specificationSet")
    public JAXBElement<SpecificationSetFactsType> createSpecificationSet(SpecificationSetFactsType value) {
        return new JAXBElement<SpecificationSetFactsType>(_SpecificationSet_QNAME, SpecificationSetFactsType.class, null, value);
    }

}
