//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.06.02 at 12:52:20 PM EST 
//


package org.yawlfoundation.sb.soundinfo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Fill_Out_Sound_SheetsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Fill_Out_Sound_SheetsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="generalInfo" type="{http://www.yawlfoundation.org/sb/soundInfo}generalInfoType"/>
 *         &lt;element name="producer" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="director" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="editor" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="soundRecordist" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="soundInfo" type="{http://www.yawlfoundation.org/sb/soundInfo}soundInfoType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Fill_Out_Sound_SheetsType", propOrder = {
    "generalInfo",
    "producer",
    "director",
    "editor",
    "soundRecordist",
    "soundInfo"
})
public class FillOutSoundSheetsType {

    @XmlElement(required = true)
    protected GeneralInfoType generalInfo;
    @XmlElement(required = true)
    protected String producer;
    @XmlElement(required = true)
    protected String director;
    @XmlElement(required = true)
    protected String editor;
    @XmlElement(required = true)
    protected String soundRecordist;
    @XmlElement(required = true)
    protected SoundInfoType soundInfo;

    /**
     * Gets the value of the generalInfo property.
     * 
     * @return
     *     possible object is
     *     {@link GeneralInfoType }
     *     
     */
    public GeneralInfoType getGeneralInfo() {
        return generalInfo;
    }

    /**
     * Sets the value of the generalInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link GeneralInfoType }
     *     
     */
    public void setGeneralInfo(GeneralInfoType value) {
        this.generalInfo = value;
    }

    /**
     * Gets the value of the producer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProducer() {
        return producer;
    }

    /**
     * Sets the value of the producer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProducer(String value) {
        this.producer = value;
    }

    /**
     * Gets the value of the director property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDirector() {
        return director;
    }

    /**
     * Sets the value of the director property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDirector(String value) {
        this.director = value;
    }

    /**
     * Gets the value of the editor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEditor() {
        return editor;
    }

    /**
     * Sets the value of the editor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEditor(String value) {
        this.editor = value;
    }

    /**
     * Gets the value of the soundRecordist property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSoundRecordist() {
        return soundRecordist;
    }

    /**
     * Sets the value of the soundRecordist property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSoundRecordist(String value) {
        this.soundRecordist = value;
    }

    /**
     * Gets the value of the soundInfo property.
     * 
     * @return
     *     possible object is
     *     {@link SoundInfoType }
     *     
     */
    public SoundInfoType getSoundInfo() {
        return soundInfo;
    }

    /**
     * Sets the value of the soundInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link SoundInfoType }
     *     
     */
    public void setSoundInfo(SoundInfoType value) {
        this.soundInfo = value;
    }

}
