//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.06.02 at 12:04:03 PM EST 
//


package org.yawlfoundation.sb.dprinfo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for ratioTimingSpecType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ratioTimingSpecType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="scheduledRatio" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dailyRatio" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="averageRatio" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="averageTiming" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="cumulative" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="originalTiming" type="{http://www.w3.org/2001/XMLSchema}time"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ratioTimingSpecType", propOrder = {
    "scheduledRatio",
    "dailyRatio",
    "averageRatio",
    "averageTiming",
    "cumulative",
    "originalTiming"
})
public class RatioTimingSpecType {

    @XmlElement(required = true)
    protected String scheduledRatio;
    @XmlElement(required = true)
    protected String dailyRatio;
    @XmlElement(required = true)
    protected String averageRatio;
    @XmlElement(required = true)
    protected String averageTiming;
    @XmlElement(required = true)
    protected String cumulative;
    @XmlElement(required = true)
    @XmlSchemaType(name = "time")
    protected XMLGregorianCalendar originalTiming;

    /**
     * Gets the value of the scheduledRatio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScheduledRatio() {
        return scheduledRatio;
    }

    /**
     * Sets the value of the scheduledRatio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScheduledRatio(String value) {
        this.scheduledRatio = value;
    }

    /**
     * Gets the value of the dailyRatio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDailyRatio() {
        return dailyRatio;
    }

    /**
     * Sets the value of the dailyRatio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDailyRatio(String value) {
        this.dailyRatio = value;
    }

    /**
     * Gets the value of the averageRatio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAverageRatio() {
        return averageRatio;
    }

    /**
     * Sets the value of the averageRatio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAverageRatio(String value) {
        this.averageRatio = value;
    }

    /**
     * Gets the value of the averageTiming property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAverageTiming() {
        return averageTiming;
    }

    /**
     * Sets the value of the averageTiming property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAverageTiming(String value) {
        this.averageTiming = value;
    }

    /**
     * Gets the value of the cumulative property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCumulative() {
        return cumulative;
    }

    /**
     * Sets the value of the cumulative property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCumulative(String value) {
        this.cumulative = value;
    }

    /**
     * Gets the value of the originalTiming property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getOriginalTiming() {
        return originalTiming;
    }

    /**
     * Sets the value of the originalTiming property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setOriginalTiming(XMLGregorianCalendar value) {
        this.originalTiming = value;
    }

}
