//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.06.02 at 12:04:03 PM EST 
//


package org.yawlfoundation.sb.dprinfo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for scenesShotInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="scenesShotInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="scenesShotToday" type="{http://www.yawlfoundation.org/sb/DPRinfo}sceneNOsType"/>
 *         &lt;element name="scenesScheduledNotShot" type="{http://www.yawlfoundation.org/sb/DPRinfo}sceneNOsType"/>
 *         &lt;element name="scenesAdded" type="{http://www.yawlfoundation.org/sb/DPRinfo}sceneNOsType"/>
 *         &lt;element name="scenesDeleted" type="{http://www.yawlfoundation.org/sb/DPRinfo}sceneNOsType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "scenesShotInfoType", propOrder = {
    "scenesShotToday",
    "scenesScheduledNotShot",
    "scenesAdded",
    "scenesDeleted"
})
public class ScenesShotInfoType {

    @XmlElement(required = true)
    protected SceneNOsType scenesShotToday;
    @XmlElement(required = true)
    protected SceneNOsType scenesScheduledNotShot;
    @XmlElement(required = true)
    protected SceneNOsType scenesAdded;
    @XmlElement(required = true)
    protected SceneNOsType scenesDeleted;

    /**
     * Gets the value of the scenesShotToday property.
     * 
     * @return
     *     possible object is
     *     {@link SceneNOsType }
     *     
     */
    public SceneNOsType getScenesShotToday() {
        return scenesShotToday;
    }

    /**
     * Sets the value of the scenesShotToday property.
     * 
     * @param value
     *     allowed object is
     *     {@link SceneNOsType }
     *     
     */
    public void setScenesShotToday(SceneNOsType value) {
        this.scenesShotToday = value;
    }

    /**
     * Gets the value of the scenesScheduledNotShot property.
     * 
     * @return
     *     possible object is
     *     {@link SceneNOsType }
     *     
     */
    public SceneNOsType getScenesScheduledNotShot() {
        return scenesScheduledNotShot;
    }

    /**
     * Sets the value of the scenesScheduledNotShot property.
     * 
     * @param value
     *     allowed object is
     *     {@link SceneNOsType }
     *     
     */
    public void setScenesScheduledNotShot(SceneNOsType value) {
        this.scenesScheduledNotShot = value;
    }

    /**
     * Gets the value of the scenesAdded property.
     * 
     * @return
     *     possible object is
     *     {@link SceneNOsType }
     *     
     */
    public SceneNOsType getScenesAdded() {
        return scenesAdded;
    }

    /**
     * Sets the value of the scenesAdded property.
     * 
     * @param value
     *     allowed object is
     *     {@link SceneNOsType }
     *     
     */
    public void setScenesAdded(SceneNOsType value) {
        this.scenesAdded = value;
    }

    /**
     * Gets the value of the scenesDeleted property.
     * 
     * @return
     *     possible object is
     *     {@link SceneNOsType }
     *     
     */
    public SceneNOsType getScenesDeleted() {
        return scenesDeleted;
    }

    /**
     * Sets the value of the scenesDeleted property.
     * 
     * @param value
     *     allowed object is
     *     {@link SceneNOsType }
     *     
     */
    public void setScenesDeleted(SceneNOsType value) {
        this.scenesDeleted = value;
    }

}
