//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-20060407-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2006.04.10 at 05:56:34 PM EDT 
//


package au.edu.qut.yawl.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FlowsIntoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FlowsIntoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="nextElementRef" type="{http://www.citi.qut.edu.au/yawl}ExternalNetElementType"/>
 *         &lt;element name="predicate" type="{http://www.citi.qut.edu.au/yawl}PredicateType" minOccurs="0"/>
 *         &lt;element name="isDefaultFlow" type="{http://www.citi.qut.edu.au/yawl}NullType" minOccurs="0"/>
 *         &lt;element name="documentation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FlowsIntoType", propOrder = {
    "nextElementRef",
    "predicate",
    "isDefaultFlow",
    "documentation"
})
public class FlowsIntoType {

    @XmlElement(namespace = "http://www.citi.qut.edu.au/yawl", required = true)
    protected ExternalNetElementType nextElementRef;
    @XmlElement(namespace = "http://www.citi.qut.edu.au/yawl")
    protected PredicateType predicate;
    @XmlElement(namespace = "http://www.citi.qut.edu.au/yawl")
    protected String isDefaultFlow;
    @XmlElement(namespace = "http://www.citi.qut.edu.au/yawl")
    protected String documentation;

    /**
     * Gets the value of the nextElementRef property.
     * 
     * @return
     *     possible object is
     *     {@link ExternalNetElementType }
     *     
     */
    public ExternalNetElementType getNextElementRef() {
        return nextElementRef;
    }

    /**
     * Sets the value of the nextElementRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExternalNetElementType }
     *     
     */
    public void setNextElementRef(ExternalNetElementType value) {
        this.nextElementRef = value;
    }

    /**
     * Gets the value of the predicate property.
     * 
     * @return
     *     possible object is
     *     {@link PredicateType }
     *     
     */
    public PredicateType getPredicate() {
        return predicate;
    }

    /**
     * Sets the value of the predicate property.
     * 
     * @param value
     *     allowed object is
     *     {@link PredicateType }
     *     
     */
    public void setPredicate(PredicateType value) {
        this.predicate = value;
    }

    /**
     * Gets the value of the isDefaultFlow property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsDefaultFlow() {
        return isDefaultFlow;
    }

    /**
     * Sets the value of the isDefaultFlow property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsDefaultFlow(String value) {
        this.isDefaultFlow = value;
    }

    /**
     * Gets the value of the documentation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentation() {
        return documentation;
    }

    /**
     * Sets the value of the documentation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentation(String value) {
        this.documentation = value;
    }

}
