//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.06.02 at 12:04:03 PM EST 
//


package org.yawlfoundation.sb.dprinfo;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.yawlfoundation.sb.dprinfo package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CreateDPR_QNAME = new QName("http://www.yawlfoundation.org/sb/DPRinfo", "Create_DPR");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.yawlfoundation.sb.dprinfo
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SingleMealType }
     * 
     */
    public SingleMealType createSingleMealType() {
        return new SingleMealType();
    }

    /**
     * Create an instance of {@link RatioTimingSpecType }
     * 
     */
    public RatioTimingSpecType createRatioTimingSpecType() {
        return new RatioTimingSpecType();
    }

    /**
     * Create an instance of {@link SingleLocationSetType }
     * 
     */
    public SingleLocationSetType createSingleLocationSetType() {
        return new SingleLocationSetType();
    }

    /**
     * Create an instance of {@link SceneShotScheduleType }
     * 
     */
    public SceneShotScheduleType createSceneShotScheduleType() {
        return new SceneShotScheduleType();
    }

    /**
     * Create an instance of {@link SingleStockInfoType }
     * 
     */
    public SingleStockInfoType createSingleStockInfoType() {
        return new SingleStockInfoType();
    }

    /**
     * Create an instance of {@link LocationSetType }
     * 
     */
    public LocationSetType createLocationSetType() {
        return new LocationSetType();
    }

    /**
     * Create an instance of {@link CateringType }
     * 
     */
    public CateringType createCateringType() {
        return new CateringType();
    }

    /**
     * Create an instance of {@link GeneralInfoType }
     * 
     */
    public GeneralInfoType createGeneralInfoType() {
        return new GeneralInfoType();
    }

    /**
     * Create an instance of {@link StockInfoType }
     * 
     */
    public StockInfoType createStockInfoType() {
        return new StockInfoType();
    }

    /**
     * Create an instance of {@link SingleCastTimeSheetInfoType }
     * 
     */
    public SingleCastTimeSheetInfoType createSingleCastTimeSheetInfoType() {
        return new SingleCastTimeSheetInfoType();
    }

    /**
     * Create an instance of {@link ScenesShotInfoType }
     * 
     */
    public ScenesShotInfoType createScenesShotInfoType() {
        return new ScenesShotInfoType();
    }

    /**
     * Create an instance of {@link SingleSceneShotScheduleType }
     * 
     */
    public SingleSceneShotScheduleType createSingleSceneShotScheduleType() {
        return new SingleSceneShotScheduleType();
    }

    /**
     * Create an instance of {@link SceneNOsType }
     * 
     */
    public SceneNOsType createSceneNOsType() {
        return new SceneNOsType();
    }

    /**
     * Create an instance of {@link SlateNOsType }
     * 
     */
    public SlateNOsType createSlateNOsType() {
        return new SlateNOsType();
    }

    /**
     * Create an instance of {@link CallWrapHRsType }
     * 
     */
    public CallWrapHRsType createCallWrapHRsType() {
        return new CallWrapHRsType();
    }

    /**
     * Create an instance of {@link CreateDPRType }
     * 
     */
    public CreateDPRType createCreateDPRType() {
        return new CreateDPRType();
    }

    /**
     * Create an instance of {@link DPRinfoType }
     * 
     */
    public DPRinfoType createDPRinfoType() {
        return new DPRinfoType();
    }

    /**
     * Create an instance of {@link CastTimeSheetInfoType }
     * 
     */
    public CastTimeSheetInfoType createCastTimeSheetInfoType() {
        return new CastTimeSheetInfoType();
    }

    /**
     * Create an instance of {@link ShootingDaysScheduleType }
     * 
     */
    public ShootingDaysScheduleType createShootingDaysScheduleType() {
        return new ShootingDaysScheduleType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateDPRType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.yawlfoundation.org/sb/DPRinfo", name = "Create_DPR")
    public JAXBElement<CreateDPRType> createCreateDPR(CreateDPRType value) {
        return new JAXBElement<CreateDPRType>(_CreateDPR_QNAME, CreateDPRType.class, null, value);
    }

}
