//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.06.02 at 12:04:03 PM EST 
//


package org.yawlfoundation.sb.dprinfo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for sceneShotScheduleType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="sceneShotScheduleType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="prevShot" type="{http://www.yawlfoundation.org/sb/DPRinfo}singleSceneShotScheduleType"/>
 *         &lt;element name="shotToday" type="{http://www.yawlfoundation.org/sb/DPRinfo}singleSceneShotScheduleType"/>
 *         &lt;element name="toDate" type="{http://www.yawlfoundation.org/sb/DPRinfo}singleSceneShotScheduleType"/>
 *         &lt;element name="toBeShot" type="{http://www.yawlfoundation.org/sb/DPRinfo}singleSceneShotScheduleType"/>
 *         &lt;element name="total" type="{http://www.yawlfoundation.org/sb/DPRinfo}singleSceneShotScheduleType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sceneShotScheduleType", propOrder = {
    "prevShot",
    "shotToday",
    "toDate",
    "toBeShot",
    "total"
})
public class SceneShotScheduleType {

    @XmlElement(required = true)
    protected SingleSceneShotScheduleType prevShot;
    @XmlElement(required = true)
    protected SingleSceneShotScheduleType shotToday;
    @XmlElement(required = true)
    protected SingleSceneShotScheduleType toDate;
    @XmlElement(required = true)
    protected SingleSceneShotScheduleType toBeShot;
    @XmlElement(required = true)
    protected SingleSceneShotScheduleType total;

    /**
     * Gets the value of the prevShot property.
     * 
     * @return
     *     possible object is
     *     {@link SingleSceneShotScheduleType }
     *     
     */
    public SingleSceneShotScheduleType getPrevShot() {
        return prevShot;
    }

    /**
     * Sets the value of the prevShot property.
     * 
     * @param value
     *     allowed object is
     *     {@link SingleSceneShotScheduleType }
     *     
     */
    public void setPrevShot(SingleSceneShotScheduleType value) {
        this.prevShot = value;
    }

    /**
     * Gets the value of the shotToday property.
     * 
     * @return
     *     possible object is
     *     {@link SingleSceneShotScheduleType }
     *     
     */
    public SingleSceneShotScheduleType getShotToday() {
        return shotToday;
    }

    /**
     * Sets the value of the shotToday property.
     * 
     * @param value
     *     allowed object is
     *     {@link SingleSceneShotScheduleType }
     *     
     */
    public void setShotToday(SingleSceneShotScheduleType value) {
        this.shotToday = value;
    }

    /**
     * Gets the value of the toDate property.
     * 
     * @return
     *     possible object is
     *     {@link SingleSceneShotScheduleType }
     *     
     */
    public SingleSceneShotScheduleType getToDate() {
        return toDate;
    }

    /**
     * Sets the value of the toDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link SingleSceneShotScheduleType }
     *     
     */
    public void setToDate(SingleSceneShotScheduleType value) {
        this.toDate = value;
    }

    /**
     * Gets the value of the toBeShot property.
     * 
     * @return
     *     possible object is
     *     {@link SingleSceneShotScheduleType }
     *     
     */
    public SingleSceneShotScheduleType getToBeShot() {
        return toBeShot;
    }

    /**
     * Sets the value of the toBeShot property.
     * 
     * @param value
     *     allowed object is
     *     {@link SingleSceneShotScheduleType }
     *     
     */
    public void setToBeShot(SingleSceneShotScheduleType value) {
        this.toBeShot = value;
    }

    /**
     * Gets the value of the total property.
     * 
     * @return
     *     possible object is
     *     {@link SingleSceneShotScheduleType }
     *     
     */
    public SingleSceneShotScheduleType getTotal() {
        return total;
    }

    /**
     * Sets the value of the total property.
     * 
     * @param value
     *     allowed object is
     *     {@link SingleSceneShotScheduleType }
     *     
     */
    public void setTotal(SingleSceneShotScheduleType value) {
        this.total = value;
    }

}
