//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.06.02 at 12:04:03 PM EST 
//


package org.yawlfoundation.sb.dprinfo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for stockInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="stockInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="previously" type="{http://www.yawlfoundation.org/sb/DPRinfo}singleStockInfoType"/>
 *         &lt;element name="today" type="{http://www.yawlfoundation.org/sb/DPRinfo}singleStockInfoType"/>
 *         &lt;element name="totalToDate" type="{http://www.yawlfoundation.org/sb/DPRinfo}singleStockInfoType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "stockInfoType", propOrder = {
    "previously",
    "today",
    "totalToDate"
})
public class StockInfoType {

    @XmlElement(required = true)
    protected SingleStockInfoType previously;
    @XmlElement(required = true)
    protected SingleStockInfoType today;
    @XmlElement(required = true)
    protected SingleStockInfoType totalToDate;

    /**
     * Gets the value of the previously property.
     * 
     * @return
     *     possible object is
     *     {@link SingleStockInfoType }
     *     
     */
    public SingleStockInfoType getPreviously() {
        return previously;
    }

    /**
     * Sets the value of the previously property.
     * 
     * @param value
     *     allowed object is
     *     {@link SingleStockInfoType }
     *     
     */
    public void setPreviously(SingleStockInfoType value) {
        this.previously = value;
    }

    /**
     * Gets the value of the today property.
     * 
     * @return
     *     possible object is
     *     {@link SingleStockInfoType }
     *     
     */
    public SingleStockInfoType getToday() {
        return today;
    }

    /**
     * Sets the value of the today property.
     * 
     * @param value
     *     allowed object is
     *     {@link SingleStockInfoType }
     *     
     */
    public void setToday(SingleStockInfoType value) {
        this.today = value;
    }

    /**
     * Gets the value of the totalToDate property.
     * 
     * @return
     *     possible object is
     *     {@link SingleStockInfoType }
     *     
     */
    public SingleStockInfoType getTotalToDate() {
        return totalToDate;
    }

    /**
     * Sets the value of the totalToDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link SingleStockInfoType }
     *     
     */
    public void setTotalToDate(SingleStockInfoType value) {
        this.totalToDate = value;
    }

}
