package editor.workflow.capsela;
/*
 * WorkflowEditor.java
 *
 * Created on May 31, 2006, 3:53 PM
 */

/**
 *
 * @author  SandozM
 */
public class WorkflowEditor extends javax.swing.JFrame {
    
    /**
     * Creates new form WorkflowEditor 
     */
    public WorkflowEditor() {
        initComponents();
        this.pack();
    	this.resize(800,600);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">                          
    private void initComponents() {
        componentEditorSplitPane = new javax.swing.JSplitPane();
        componentListPanel = new javax.swing.JPanel();
        componentListScrollPane = new javax.swing.JScrollPane();
        componentListTree = new javax.swing.JTree();
        desktopAndStatusPanel = new javax.swing.JPanel();
        desktopLogSplitPane = new javax.swing.JSplitPane();
        desktopPanel = new javax.swing.JPanel();
        desktopScrollPane = new javax.swing.JScrollPane();
        desktopPane = new javax.swing.JDesktopPane();
        logPanel = new javax.swing.JPanel();
        logTextScrollPane = new javax.swing.JScrollPane();
        logTextArea = new javax.swing.JTextArea();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentsMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Workflow Editor");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.lightGray);
        setName("Workflow Editor");
        componentEditorSplitPane.setDividerLocation(100);
        componentListPanel.setLayout(new java.awt.BorderLayout());

        componentListScrollPane.setMinimumSize(new java.awt.Dimension(0, 0));
        componentListTree.setEnabled(false);
        componentListTree.setPreferredSize(null);
        componentListScrollPane.setViewportView(componentListTree);

        componentListPanel.add(componentListScrollPane, java.awt.BorderLayout.CENTER);

        componentEditorSplitPane.setLeftComponent(componentListPanel);

        desktopAndStatusPanel.setLayout(new java.awt.GridLayout(1, 0));

        desktopLogSplitPane.setDividerLocation(500);
        desktopLogSplitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        desktopLogSplitPane.setRequestFocusEnabled(false);
        desktopPanel.setLayout(new java.awt.GridLayout(1, 0));

        desktopPane.setBackground(new java.awt.Color(135, 145, 161));
        desktopScrollPane.setViewportView(desktopPane);

        desktopPanel.add(desktopScrollPane);

        desktopLogSplitPane.setTopComponent(desktopPanel);

        logPanel.setLayout(new java.awt.GridLayout(1, 0));

        logTextArea.setRows(4);
        logTextArea.setText("Log Message");
        logTextArea.setPreferredSize(null);
        logTextScrollPane.setViewportView(logTextArea);

        logPanel.add(logTextScrollPane);

        desktopLogSplitPane.setBottomComponent(logPanel);

        desktopAndStatusPanel.add(desktopLogSplitPane);

        componentEditorSplitPane.setRightComponent(desktopAndStatusPanel);

        getContentPane().add(componentEditorSplitPane, java.awt.BorderLayout.CENTER);

        fileMenu.setText("File");
        openMenuItem.setText("Open");
        fileMenu.add(openMenuItem);

        saveMenuItem.setText("Save");
        fileMenu.add(saveMenuItem);

        saveAsMenuItem.setText("Save As ...");
        fileMenu.add(saveAsMenuItem);

        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });

        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setText("Edit");
        cutMenuItem.setText("Cut");
        editMenu.add(cutMenuItem);

        copyMenuItem.setText("Copy");
        editMenu.add(copyMenuItem);

        pasteMenuItem.setText("Paste");
        editMenu.add(pasteMenuItem);

        deleteMenuItem.setText("Delete");
        editMenu.add(deleteMenuItem);

        menuBar.add(editMenu);

        helpMenu.setText("Help");
        contentsMenuItem.setText("Contents");
        helpMenu.add(contentsMenuItem);

        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        pack();
    }
    // </editor-fold>                        

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {                                             
        System.exit(0);
    }                                            
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
    public void run() {
                new WorkflowEditor().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify                     
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JSplitPane componentEditorSplitPane;
    private javax.swing.JPanel componentListPanel;
    private javax.swing.JScrollPane componentListScrollPane;
    private javax.swing.JTree componentListTree;
    private javax.swing.JMenuItem contentsMenuItem;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JPanel desktopAndStatusPanel;
    private javax.swing.JSplitPane desktopLogSplitPane;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JPanel desktopPanel;
    private javax.swing.JScrollPane desktopScrollPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JPanel logPanel;
    private javax.swing.JTextArea logTextArea;
    private javax.swing.JScrollPane logTextScrollPane;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem pasteMenuItem;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    // End of variables declaration                   
    
}
