package org.yawlfoundation.yawl.stateless.listener.event;

/**
 * @author Michael Adams
 * @date 24/8/20
 */
public enum YEventType {
    ITEM_ENABLED,
    ITEM_STARTED,
    ITEM_COMPLETED,
    ITEM_STATUS_CHANGE,
    ITEM_CANCEL,
    ITEM_DATA_VALUE_CHANGE,
    CASE_START,
    CASE_COMPLETE,
    CASE_CANCELLED,
    CASE_DEADLOCKED,
    CASE_SUSPENDING,
    CASE_SUSPENDED,
    CASE_RESUMED,
    TIMER_EXPIRED,
    ITEM_CHECK_PRECONSTRAINTS,
    ITEM_CHECK_POSTCONSTRAINTS,
    CASE_CHECK_PRECONSTRAINTS,
    CASE_CHECK_POSTCONSTRAINTS,
    ITEM_ABORT,
    NET_STARTED,
    NET_CANCELLED,
    NET_COMPLETED,
    NO_EVENT
}
