//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.05.22 at 10:45:47 AM EST 
//


package org.yawlfoundation.sb.camerainfo;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for camInfoSumType_1 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="camInfoSumType_1">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="footageLoaded" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="totalExposed" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="shortEnds" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="waste" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "camInfoSumType_1", propOrder = {
    "footageLoaded",
    "totalExposed",
    "shortEnds",
    "waste"
})
public class CamInfoSumType1 {

    @XmlElement(required = true)
    protected BigInteger footageLoaded;
    @XmlElement(required = true)
    protected BigInteger totalExposed;
    @XmlElement(required = true)
    protected BigInteger shortEnds;
    @XmlElement(required = true)
    protected BigInteger waste;

    /**
     * Gets the value of the footageLoaded property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFootageLoaded() {
        return footageLoaded;
    }

    /**
     * Sets the value of the footageLoaded property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFootageLoaded(BigInteger value) {
        this.footageLoaded = value;
    }

    /**
     * Gets the value of the totalExposed property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTotalExposed() {
        return totalExposed;
    }

    /**
     * Sets the value of the totalExposed property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTotalExposed(BigInteger value) {
        this.totalExposed = value;
    }

    /**
     * Gets the value of the shortEnds property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getShortEnds() {
        return shortEnds;
    }

    /**
     * Sets the value of the shortEnds property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setShortEnds(BigInteger value) {
        this.shortEnds = value;
    }

    /**
     * Gets the value of the waste property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getWaste() {
        return waste;
    }

    /**
     * Sets the value of the waste property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setWaste(BigInteger value) {
        this.waste = value;
    }

}
