//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.05.22 at 10:45:47 AM EST 
//


package org.yawlfoundation.sb.camerainfo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Fill_Out_Camera_SheetsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Fill_Out_Camera_SheetsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="generalInfo" type="{http://www.yawlfoundation.org/sb/cameraInfo}generalInfoType"/>
 *         &lt;element name="producer" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="director" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="directorOfPhotography" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="cameraOperator" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="cameraAssistant" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="cameraInfo" type="{http://www.yawlfoundation.org/sb/cameraInfo}cameraInfoType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Fill_Out_Camera_SheetsType", propOrder = {
    "generalInfo",
    "producer",
    "director",
    "directorOfPhotography",
    "cameraOperator",
    "cameraAssistant",
    "cameraInfo"
})
public class FillOutCameraSheetsType {

    @XmlElement(required = true)
    protected GeneralInfoType generalInfo;
    @XmlElement(required = true)
    protected String producer;
    @XmlElement(required = true)
    protected String director;
    @XmlElement(required = true)
    protected String directorOfPhotography;
    @XmlElement(required = true)
    protected String cameraOperator;
    @XmlElement(required = true)
    protected String cameraAssistant;
    @XmlElement(required = true)
    protected CameraInfoType cameraInfo;

    /**
     * Gets the value of the generalInfo property.
     * 
     * @return
     *     possible object is
     *     {@link GeneralInfoType }
     *     
     */
    public GeneralInfoType getGeneralInfo() {
        return generalInfo;
    }

    /**
     * Sets the value of the generalInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link GeneralInfoType }
     *     
     */
    public void setGeneralInfo(GeneralInfoType value) {
        this.generalInfo = value;
    }

    /**
     * Gets the value of the producer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProducer() {
        return producer;
    }

    /**
     * Sets the value of the producer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProducer(String value) {
        this.producer = value;
    }

    /**
     * Gets the value of the director property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDirector() {
        return director;
    }

    /**
     * Sets the value of the director property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDirector(String value) {
        this.director = value;
    }

    /**
     * Gets the value of the directorOfPhotography property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDirectorOfPhotography() {
        return directorOfPhotography;
    }

    /**
     * Sets the value of the directorOfPhotography property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDirectorOfPhotography(String value) {
        this.directorOfPhotography = value;
    }

    /**
     * Gets the value of the cameraOperator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCameraOperator() {
        return cameraOperator;
    }

    /**
     * Sets the value of the cameraOperator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCameraOperator(String value) {
        this.cameraOperator = value;
    }

    /**
     * Gets the value of the cameraAssistant property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCameraAssistant() {
        return cameraAssistant;
    }

    /**
     * Sets the value of the cameraAssistant property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCameraAssistant(String value) {
        this.cameraAssistant = value;
    }

    /**
     * Gets the value of the cameraInfo property.
     * 
     * @return
     *     possible object is
     *     {@link CameraInfoType }
     *     
     */
    public CameraInfoType getCameraInfo() {
        return cameraInfo;
    }

    /**
     * Sets the value of the cameraInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link CameraInfoType }
     *     
     */
    public void setCameraInfo(CameraInfoType value) {
        this.cameraInfo = value;
    }

}
