//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.05.22 at 10:45:47 AM EST 
//


package org.yawlfoundation.sb.camerainfo;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.yawlfoundation.sb.camerainfo package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _FillOutCameraSheets_QNAME = new QName("http://www.yawlfoundation.org/sb/cameraInfo", "Fill_Out_Camera_Sheets");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.yawlfoundation.sb.camerainfo
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CameraInfoType }
     * 
     */
    public CameraInfoType createCameraInfoType() {
        return new CameraInfoType();
    }

    /**
     * Create an instance of {@link GeneralInfoType }
     * 
     */
    public GeneralInfoType createGeneralInfoType() {
        return new GeneralInfoType();
    }

    /**
     * Create an instance of {@link FillOutCameraSheetsType }
     * 
     */
    public FillOutCameraSheetsType createFillOutCameraSheetsType() {
        return new FillOutCameraSheetsType();
    }

    /**
     * Create an instance of {@link SlateInfoType }
     * 
     */
    public SlateInfoType createSlateInfoType() {
        return new SlateInfoType();
    }

    /**
     * Create an instance of {@link TechInfoType }
     * 
     */
    public TechInfoType createTechInfoType() {
        return new TechInfoType();
    }

    /**
     * Create an instance of {@link CamInfoSumType2 }
     * 
     */
    public CamInfoSumType2 createCamInfoSumType2() {
        return new CamInfoSumType2();
    }

    /**
     * Create an instance of {@link CamInfoSumType3 }
     * 
     */
    public CamInfoSumType3 createCamInfoSumType3() {
        return new CamInfoSumType3();
    }

    /**
     * Create an instance of {@link CamInfoSumType1 }
     * 
     */
    public CamInfoSumType1 createCamInfoSumType1() {
        return new CamInfoSumType1();
    }

    /**
     * Create an instance of {@link TakeInfoType }
     * 
     */
    public TakeInfoType createTakeInfoType() {
        return new TakeInfoType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FillOutCameraSheetsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.yawlfoundation.org/sb/cameraInfo", name = "Fill_Out_Camera_Sheets")
    public JAXBElement<FillOutCameraSheetsType> createFillOutCameraSheets(FillOutCameraSheetsType value) {
        return new JAXBElement<FillOutCameraSheetsType>(_FillOutCameraSheets_QNAME, FillOutCameraSheetsType.class, null, value);
    }

}
