//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.06.03 at 03:09:30 PM EST 
//


package org.yawlfoundation.sb.timesheetinfo;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for childrenTimeSheetType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="childrenTimeSheetType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="singleChildren" type="{http://www.yawlfoundation.org/sb/timeSheetInfo}singleChildrenType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "childrenTimeSheetType", propOrder = {
    "singleChildren"
})
public class ChildrenTimeSheetType {

    protected List<SingleChildrenType> singleChildren;

    /**
     * Gets the value of the singleChildren property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the singleChildren property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSingleChildren().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SingleChildrenType }
     * 
     * 
     */
    public List<SingleChildrenType> getSingleChildren() {
        if (singleChildren == null) {
            singleChildren = new ArrayList<SingleChildrenType>();
        }
        return this.singleChildren;
    }

}
