//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.06.03 at 03:09:30 PM EST 
//


package org.yawlfoundation.sb.timesheetinfo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for singleArtistType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="singleArtistType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="artist" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="P_U" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MU_WD_Call_scheduled" type="{http://www.w3.org/2001/XMLSchema}time"/>
 *         &lt;element name="MU_WD_Call_actualArrival" type="{http://www.w3.org/2001/XMLSchema}time"/>
 *         &lt;element name="mealBreak" type="{http://www.w3.org/2001/XMLSchema}time"/>
 *         &lt;element name="timeWrap" type="{http://www.w3.org/2001/XMLSchema}time"/>
 *         &lt;element name="travel" type="{http://www.w3.org/2001/XMLSchema}time"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "singleArtistType", propOrder = {
    "artist",
    "pu",
    "muwdCallScheduled",
    "muwdCallActualArrival",
    "mealBreak",
    "timeWrap",
    "travel"
})
public class SingleArtistType {

    @XmlElement(required = true)
    protected String artist;
    @XmlElement(name = "P_U", required = true)
    protected String pu;
    @XmlElement(name = "MU_WD_Call_scheduled", required = true)
    @XmlSchemaType(name = "time")
    protected XMLGregorianCalendar muwdCallScheduled;
    @XmlElement(name = "MU_WD_Call_actualArrival", required = true)
    @XmlSchemaType(name = "time")
    protected XMLGregorianCalendar muwdCallActualArrival;
    @XmlElement(required = true)
    @XmlSchemaType(name = "time")
    protected XMLGregorianCalendar mealBreak;
    @XmlElement(required = true)
    @XmlSchemaType(name = "time")
    protected XMLGregorianCalendar timeWrap;
    @XmlElement(required = true)
    @XmlSchemaType(name = "time")
    protected XMLGregorianCalendar travel;

    /**
     * Gets the value of the artist property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArtist() {
        return artist;
    }

    /**
     * Sets the value of the artist property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArtist(String value) {
        this.artist = value;
    }

    /**
     * Gets the value of the pu property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPU() {
        return pu;
    }

    /**
     * Sets the value of the pu property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPU(String value) {
        this.pu = value;
    }

    /**
     * Gets the value of the muwdCallScheduled property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getMUWDCallScheduled() {
        return muwdCallScheduled;
    }

    /**
     * Sets the value of the muwdCallScheduled property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setMUWDCallScheduled(XMLGregorianCalendar value) {
        this.muwdCallScheduled = value;
    }

    /**
     * Gets the value of the muwdCallActualArrival property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getMUWDCallActualArrival() {
        return muwdCallActualArrival;
    }

    /**
     * Sets the value of the muwdCallActualArrival property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setMUWDCallActualArrival(XMLGregorianCalendar value) {
        this.muwdCallActualArrival = value;
    }

    /**
     * Gets the value of the mealBreak property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getMealBreak() {
        return mealBreak;
    }

    /**
     * Sets the value of the mealBreak property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setMealBreak(XMLGregorianCalendar value) {
        this.mealBreak = value;
    }

    /**
     * Gets the value of the timeWrap property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTimeWrap() {
        return timeWrap;
    }

    /**
     * Sets the value of the timeWrap property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTimeWrap(XMLGregorianCalendar value) {
        this.timeWrap = value;
    }

    /**
     * Gets the value of the travel property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTravel() {
        return travel;
    }

    /**
     * Sets the value of the travel property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTravel(XMLGregorianCalendar value) {
        this.travel = value;
    }

}
