package org.yawlfoundation.yawl.editor.actions.element;

import org.jdesktop.layout.GroupLayout;
import org.jdesktop.layout.LayoutStyle;
import org.yawlfoundation.yawl.editor.YAWLEditor;
import org.yawlfoundation.yawl.editor.actions.YAWLBaseAction;
import org.yawlfoundation.yawl.editor.elements.model.YAWLTask;
import org.yawlfoundation.yawl.editor.net.NetGraph;
import org.yawlfoundation.yawl.editor.swing.TooltipTogglingWidget;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;

public class CancellationRegionConfigurationAction extends YAWLBaseAction
        implements TooltipTogglingWidget {

	{
	    putValue(Action.SHORT_DESCRIPTION, getDisabledTooltipText());
	    putValue(Action.NAME, "Cancellation Region...");
	    putValue(Action.LONG_DESCRIPTION, "Configure the cancellation region for this task.");
      putValue(Action.SMALL_ICON, getPNGIcon("comment_delete"));
	    
	  }
	
	private YAWLTask task;
	private NetGraph net;
	
	
	public CancellationRegionConfigurationAction(YAWLTask task){
		this.task = task;
		this.net = this.getGraph();
	}
	
	public void actionPerformed(ActionEvent event) {  
	  	final YAWLTask task = this.task;
	 	  final NetGraph net = this.net;
		  java.awt.EventQueue.invokeLater(new Runnable() {
	        public void run() {
	            ConfigureCancellationSetJDialog dialog =
                      new ConfigureCancellationSetJDialog(new javax.swing.JFrame(), true, task, net);
	            dialog.addWindowListener(new java.awt.event.WindowAdapter() {});
	            dialog.setLocationRelativeTo(YAWLEditor.getInstance());
	            dialog.setMinimumSize(dialog.getSize());
	            dialog.setPreferredSize(dialog.getSize());
              dialog.setResizable(false);
	            dialog.setVisible(true);
	        }
	    });
}

	public String getDisabledTooltipText() {
		return null;
	}


	public String getEnabledTooltipText() {
		return "Configure the cancellation region for this task.";
	}
	

	
	private class ConfigureCancellationSetJDialog extends javax.swing.JDialog {
		
		private YAWLTask task;
		private NetGraph net;
	    
	    /** Creates new form ConfigureCancellationSetJDialog */
	    public ConfigureCancellationSetJDialog(java.awt.Frame parent, boolean modal,
                                             YAWLTask task, NetGraph net) {
	    	super(parent, modal);
	    	this.task = task;
	    	this.net = net;  
	    	this.setTitle("Configuration Set Configuration");
	      initComponents();
	    }
	    
	    /** This method is called from within the constructor to
	     * initialize the form.
	     * WARNING: Do NOT modify this code. The content of this method is
	     * always regenerated by the Form Editor.
	     */
	    @SuppressWarnings("unchecked")
	    // <editor-fold defaultstate="collapsed" desc="Generated Code">
	    private void initComponents() {
	    	this.setTitle("Cancellation Region Configuration");
	        jLabel1 = new javax.swing.JLabel();
	        jTextField1 = new javax.swing.JTextField();
	        AllowButton = new javax.swing.JButton();
	        BlockButton = new javax.swing.JButton();

	        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

	        jLabel1.setText("Value");

	        jTextField1.setEditable(false);

	        AllowButton.setText("Activated");
	        AllowButton.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                AllowButtonActionPerformed(evt);
	            }
	        });

	        BlockButton.setText("Block");
	        BlockButton.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                BlockButtonActionPerformed(evt);
	            }
	        });

	        GroupLayout layout = new GroupLayout(getContentPane());
	        getContentPane().setLayout(layout);
	        layout.setHorizontalGroup(
	            layout.createParallelGroup(GroupLayout.LEADING)
	            .add(layout.createSequentialGroup()
	                .add(layout.createParallelGroup(GroupLayout.LEADING)
	                    .add(layout.createSequentialGroup()
	                        .add(37, 37, 37)
	                        .add(jLabel1, GroupLayout.PREFERRED_SIZE, 64, GroupLayout.PREFERRED_SIZE)
	                        .addPreferredGap(LayoutStyle.UNRELATED)
	                        .add(jTextField1, GroupLayout.PREFERRED_SIZE, 107, GroupLayout.PREFERRED_SIZE))
	                    .add(layout.createSequentialGroup()
	                        .add(29, 29, 29)
	                        .add(AllowButton)
	                        .add(18, 18, 18)
	                        .add(BlockButton)))
	                .addContainerGap(28, Short.MAX_VALUE))
	        );
	        layout.setVerticalGroup(
	            layout.createParallelGroup(GroupLayout.LEADING)
	            .add(layout.createSequentialGroup()
	                .add(39, 39, 39)
	                .add(layout.createParallelGroup(GroupLayout.BASELINE)
	                    .add(jLabel1, GroupLayout.PREFERRED_SIZE, 27, GroupLayout.PREFERRED_SIZE)
	                    .add(jTextField1, GroupLayout.PREFERRED_SIZE, 23, GroupLayout.PREFERRED_SIZE))
	                .add(18, 18, 18)
	                .add(layout.createParallelGroup(GroupLayout.BASELINE)
	                    .add(AllowButton)
	                    .add(BlockButton))
	                .addContainerGap(16, Short.MAX_VALUE))
	        );
	        if (this.task.isCancellationSetEnable()){
	        	this.jTextField1.setText("activated");
	        	this.jTextField1.setForeground(new Color(8,84,8));
	        }else{
	        	this.jTextField1.setText("blocked");
	        	this.jTextField1.setForeground(Color.red);
	        }
	        
	        pack();
	    }// </editor-fold>

	private void AllowButtonActionPerformed(java.awt.event.ActionEvent evt) {
		this.jTextField1.setText("activated");
		this.task.setCancellationSetEnable(true);
		this.jTextField1.setForeground(new Color(8,84,8));
	}

	private void BlockButtonActionPerformed(java.awt.event.ActionEvent evt) {
		this.jTextField1.setText("blocked");
		this.task.setCancellationSetEnable(false);
		this.jTextField1.setForeground(Color.red);
	}
	    
	   
	    
	    // Variables declaration - do not modify
	    private javax.swing.JButton AllowButton;
	    private javax.swing.JButton BlockButton;
	    private javax.swing.JLabel jLabel1;
	    private javax.swing.JTextField jTextField1;
	    // End of variables declaration
	    
	}

}
