//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.06.02 at 01:01:41 PM EST 
//


package org.yawlfoundation.sb.callsheetinfo;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for singleSceneShootingType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="singleSceneShootingType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="scene" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="D_N_Time" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Int_Ext_D_N_Set_Synopsis" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="singleCastInfoCall" type="{http://www.yawlfoundation.org/sb/callSheetInfo}singleCastInfoCallType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "singleSceneShootingType", propOrder = {
    "scene",
    "dnTime",
    "intExtDNSetSynopsis",
    "singleCastInfoCall"
})
public class SingleSceneShootingType {

    @XmlElement(required = true)
    protected String scene;
    @XmlElement(name = "D_N_Time", required = true)
    protected String dnTime;
    @XmlElement(name = "Int_Ext_D_N_Set_Synopsis", required = true)
    protected String intExtDNSetSynopsis;
    @XmlElement(required = true)
    protected List<SingleCastInfoCallType> singleCastInfoCall;

    /**
     * Gets the value of the scene property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScene() {
        return scene;
    }

    /**
     * Sets the value of the scene property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScene(String value) {
        this.scene = value;
    }

    /**
     * Gets the value of the dnTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDNTime() {
        return dnTime;
    }

    /**
     * Sets the value of the dnTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDNTime(String value) {
        this.dnTime = value;
    }

    /**
     * Gets the value of the intExtDNSetSynopsis property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIntExtDNSetSynopsis() {
        return intExtDNSetSynopsis;
    }

    /**
     * Sets the value of the intExtDNSetSynopsis property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIntExtDNSetSynopsis(String value) {
        this.intExtDNSetSynopsis = value;
    }

    /**
     * Gets the value of the singleCastInfoCall property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the singleCastInfoCall property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSingleCastInfoCall().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SingleCastInfoCallType }
     * 
     * 
     */
    public List<SingleCastInfoCallType> getSingleCastInfoCall() {
        if (singleCastInfoCall == null) {
            singleCastInfoCall = new ArrayList<SingleCastInfoCallType>();
        }
        return this.singleCastInfoCall;
    }

}
