/*
 * This file is made available under the terms of the LGPL licence.
 * This licence can be retrieved from http://www.gnu.org/copyleft/lesser.html.
 * The source remains the property of the YAWL Foundation.  The YAWL Foundation is a collaboration of
 * individuals and organisations who are committed to improving workflow technology.
 *
 */


package org.yawlfoundation.yawl.admintool.model;

import org.hibernate.Session;
import org.hibernate.HibernateException;
import org.hibernate.Transaction;

import java.io.Serializable;
import java.sql.Statement;

/**
 * 
 * @author Lachlan Aldred
 * Date: 23/09/2005
 * Time: 14:46:43
 */
public class HumanResourceRole implements Serializable {
    private Resource humanResource;
    private Role role;

    public HumanResourceRole() {
    }

    public Resource getHumanResource() {
        return humanResource;
    }

    public void setHumanResource(Resource humanResource) {
        if(humanResource instanceof HumanResource) {
            this.humanResource = humanResource;
        } else {
            throw new IllegalArgumentException("<resource> is not instance of HumanResource");
        }
    }

    public Role getRole() {
        return role;
    }

    public void setRole(Role role) {
        this.role = role;
    }

    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof HumanResourceRole)) return false;

        final HumanResourceRole humanResourceRole = (HumanResourceRole) o;

        if (!humanResource.equals(humanResourceRole.humanResource)) return false;
        if (!role.equals(humanResourceRole.role)) return false;

        return true;
    }

    public int hashCode() {
        int result;
        result = humanResource.hashCode();
        result = 29 * result + role.hashCode();
        return result;
    }


    /**
     * This hack ensures that referential integrity is maintained.  It dropps
     * the table generated by hibernate and replaces it with a better one.
     * @param session
     */
    public static void addIntegrityEnforcements(Session session) throws HibernateException {
        Transaction tx = null;
        try {
            tx = session.beginTransaction();
            Statement st = session.connection().createStatement();
            st.executeUpdate(
                "DROP TABLE hresperformsrole;" +
                "CREATE TABLE hresperformsrole" +
                "(" +
                  "hresid varchar(255) NOT NULL," +
                  "rolename varchar(255) NOT NULL," +
                  "CONSTRAINT hresperformsrole_pkey PRIMARY KEY (hresid, rolename)," +
                  "CONSTRAINT ResourceFK FOREIGN KEY (hresid) REFERENCES resserposid (id) ON UPDATE CASCADE ON DELETE CASCADE," +
                  "CONSTRAINT RoleFK FOREIGN KEY (rolename) REFERENCES role (rolename) ON UPDATE CASCADE ON DELETE CASCADE" +
                ");"
            );
            tx.commit();
        } catch (Exception e) {
            tx.rollback();
        }
    }
}
