/*
 * Copyright (c) 2004-2013 The YAWL Foundation. All rights reserved.
 * The YAWL Foundation is a collaboration of individuals and
 * organisations who are committed to improving workflow technology.
 *
 * This file is part of YAWL. YAWL is free software: you can
 * redistribute it and/or modify it under the terms of the GNU Lesser
 * General Public License as published by the Free Software Foundation.
 *
 * YAWL is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General
 * Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with YAWL. If not, see <http://www.gnu.org/licenses/>.
 */

package org.yawlfoundation.yawl.editor.core.repository;

import org.yawlfoundation.yawl.editor.core.layout.YLayout;
import org.yawlfoundation.yawl.editor.core.layout.YNetLayout;
import org.yawlfoundation.yawl.editor.ui.specification.io.LayoutExporter;
import org.yawlfoundation.yawl.elements.*;
import org.yawlfoundation.yawl.exceptions.YSyntaxException;
import org.yawlfoundation.yawl.unmarshal.YMarshal;
import org.yawlfoundation.yawl.util.StringUtil;
import org.yawlfoundation.yawl.util.XNode;
import org.yawlfoundation.yawl.util.XNodeParser;

import java.util.*;

/**
 * @author Michael Adams
 * @date 6/08/13
 */
public class NetRepository extends DecompositionRepoMap {

    protected NetRepository() {
        super("netDecompositions");
    }

    protected NetRepository(String baseDir) {
        super(baseDir, "netDecompositions");
    }

    /**
     * Adds a net decomposition to the repository
     * @param name a reference name for the net decomposition
     * @param description a description of it
     * @param net the net decomposition to add
     * @return whether the add was successful
     */
    public String add(String name, String description, YNet net) {
        String uniqueName = super.add(name, description, net);
        Set<String> containedIds = addContainedDecompositions(net);
        if (! containedIds.isEmpty()) {
            addDecompositionIdMappings(uniqueName, containedIds);
        }
        String layoutXML = getNetLayoutXML(net);
        if (layoutXML != null) {
            addLayout(uniqueName, layoutXML);
        }
        if (! (containedIds.isEmpty() && layoutXML == null)) {
            save();   // updates
        }
        return uniqueName;
    }


    /**
     * Gets a net decomposition from the repository
     * @param name a reference name for the net decomposition
     * @return the referenced net decomposition, or null if not found
     */
    public Map<String, YDecomposition> getNetAndDecompositions(String name)
            throws YSyntaxException {
        RepoRecord record = getRecord(name);
        return record != null ? parseNetRecord(record) :
                Collections.<String, YDecomposition>emptyMap();
    }


    public XNode getLayout(String name) throws YSyntaxException {
        RepoRecord record = getRecord(name);
        if (record != null) {
            XNode rootNode = parseRecord(record.getValue());
            return rootNode != null ? rootNode.getChild("layout") : null;
        }
        return null;
    }


    /**
     * Gets a decomposition from the repository
     * @param name a reference name for the decomposition
     * @return the referenced decomposition, or null if not found
     */
    public YNet get(String name) throws YSyntaxException {
        return (YNet) super.get(name);
    }


    /**
     * Removes a net decomposition from the repository
     * @param name a reference name for the net decomposition
     * @return whether the removal was successful
     */
    public YNet remove(String name) {
        return (YNet) super.remove(name);
    }


    /**
     * Gets a sorted list of descriptors for all stored net decompositions
     * @return A sorted list of RepoDescriptors (String pairs - name, description)
     */
    public List<RepoDescriptor> getDescriptors() {
        return super.getDescriptors();
    }


    // Writes a net decomposition to xml. Since a specification adds some xml to that
    // generated by a decomposition, we have to replicate it here
    protected String toXML(YDecomposition decomposition) {
        YNet net = (YNet) decomposition;
        XNode netNode = new XNode("decomposition");
        netNode.addAttribute("id", net.getID());
        netNode.addContent(net.toXML());
        return netNode.toString();
    }


    protected void addXsiAttribute(XNode decompositionNode) {
        decompositionNode.addAttribute("xsi:type", "NetFactsType");
    }


    protected boolean addDecompositionIdMappings(String name, Set<String> ids) {
        RepoRecord record = getRecord(name);
        if (record != null) {
            record.setValue(convertToXML(ids) + record.getValue());
        }
        return record != null;
    }


    protected boolean addLayout(String name, String layoutXML) {
        RepoRecord record = getRecord(name);
        if (record != null) {
            record.setValue(record.getValue() + StringUtil.wrap(layoutXML, "layout"));
        }
        return record != null;
    }


    protected Set<String> addContainedDecompositions(YNet net) {
        Set<String> idSet = new HashSet<String>();
        String description = "Stored as required by storage of " + net.getID();
        for (YTask task : net.getNetTasks()) {
            YDecomposition decomposition = task.getDecompositionPrototype();
            if (decomposition == null) continue;

            String currentID = decomposition.getID();
            String uniqueID = null;
            if (decomposition instanceof YAWLServiceGateway) {
                uniqueID = YRepository.getInstance().getTaskDecompositionRepository().add(
                        currentID, description, (YAWLServiceGateway) decomposition);
            }
            else if (decomposition instanceof YNet) {

                // recurse for subnets
                uniqueID = add(decomposition.getID(), description, (YNet) decomposition);
            }
            idSet.add(uniqueID);
        }
        return idSet;
    }


    protected XNode parseRecord(String xml) throws YSyntaxException {
        if (xml == null) return null;
        if (parser == null) parser = new XNodeParser();
        xml = StringUtil.wrap(xml, "temp");
        XNode rootNode = parser.parse(xml);
        if (rootNode == null) {
            throw new YSyntaxException("Invalid repository record structure.");
        }
        return rootNode;
    }

    /**
     * Creates a decomposition from its XML description
     * @param record the RepoRecord to parse
     * @return the populated task decomposition
     */
    protected Map<String, YDecomposition> parseNetRecord(RepoRecord record)
            throws YSyntaxException {
        Map<String, XNode> nodeMap = parseDecompositionNodes(record);
        Map<String, String> netIDtoRepoIDMap = extractIDMap(nodeMap);

        XNode specNode = getSpecificationNode();
        specNode.addChildren(nodeMap.values());

        YSpecification specification = YMarshal.unmarshalSpecifications(
                shellSpecification.toString(true), false).get(0);

        resetSpecificationNode();                       // reset shell for next time

        Map<String, YDecomposition> decoMap = new HashMap<String, YDecomposition>();
        for (YDecomposition decomposition : specification.getDecompositions()) {
            if (! decomposition.getID().equals("rootNet")) {
                String repoID = netIDtoRepoIDMap.get(decomposition.getID());
                decoMap.put(repoID, decomposition);
            }
        }
        return decoMap;
    }


    protected Map<String, XNode> parseDecompositionNodes(RepoRecord record)
            throws YSyntaxException {
        Map<String, XNode> parsedNodes = new HashMap<String, XNode>();
        XNode rootNode = parseRecord(record.getValue());
        XNode netNode = rootNode.getChild("decomposition");
        if (netNode != null) {
            XNode taskDecompositionsNode = rootNode.getChild("taskDecompositions");
            parsedNodes.putAll(parseDecompositionNodes(record.getName(),
                    netNode, taskDecompositionsNode));
        }
        return parsedNodes;
    }


    protected Map<String, XNode> parseDecompositionNodes(String repoID, XNode netNode,
                                                 XNode taskDecompositionsNode)
                throws YSyntaxException {
        Map<String, XNode> parsedNodes = new HashMap<String, XNode>();
        addXsiAttribute(netNode);
        parsedNodes.put(repoID, netNode);
        String netID = netNode.getAttributeValue("id");
        for (RepoRecord record : extractSubNetRecords(taskDecompositionsNode, netID)) {
            parsedNodes.putAll(parseDecompositionNodes(record));  // recurse for subnets
        }
        for (RepoRecord record : extractTaskDecompositionRecords(taskDecompositionsNode)) {
            XNode decompositionNode = parser.parse(record.getValue());
            if (decompositionNode != null) {
                decompositionNode.addAttribute("xsi:type", "WebServiceGatewayFactsType");
                parsedNodes.put(record.getName(), decompositionNode);
            }
        }
        return parsedNodes;
    }


    protected XNode getSpecificationNode() throws YSyntaxException {
        if (shellSpecification == null) shellSpecification = createShellSpecification();
        XNode specNode = shellSpecification.getChild("specification");
        if (specNode == null) {
            throw new YSyntaxException("Invalid repository record structure.");
        }
        return specNode;
    }

    protected void resetSpecificationNode() throws YSyntaxException{
        XNode specNode = getSpecificationNode();
        Set<XNode> toRemove = new HashSet<XNode>();
        for (XNode child : specNode.getChildren("decomposition")) {
            if (child.getAttributeValue("isRootNet") == null) {
                toRemove.add(child);
            }
        }
        for (XNode node : toRemove) specNode.removeChild(node);
    }


    private String convertToXML(Set<String> ids) {
        XNode node = new XNode("taskDecompositions");
        for (String id : ids) {
            node.addChild("id", id);
        }
        return node.toPrettyString();
    }


    private Set<RepoRecord> extractTaskDecompositionRecords(XNode node) {
        if (node == null) return Collections.emptySet();

        Set<String> nameSet = new HashSet<String>();
        for (XNode child : node.getChildren()) {
             nameSet.add(child.getText());
        }
        return YRepository.getInstance().getTaskDecompositionRepository()
                .getValues(nameSet);
    }


    private Set<RepoRecord> extractSubNetRecords(XNode node, String netID) {
        if (node == null) return Collections.emptySet();

        Set<RepoRecord> recordSet = new HashSet<RepoRecord>();
        Set<XNode> toRemove = new HashSet<XNode>();
        for (XNode child : node.getChildren()) {
            RepoRecord record = getRecord(child.getText());
            if (record != null) {
                String desc = record.getDescription();
                if (desc != null && desc.equals("Stored as required by storage of " + netID)) {
                    recordSet.add(record);
                    toRemove.add(child);
                }
            }
        }

        for (XNode child : toRemove) node.removeChild(child);
        return recordSet;
    }


    private Map<String, String> extractIDMap(Map<String, XNode> nodeMap) {
        Map<String, String> idMap = new HashMap<String, String>();
        for (String repoID : nodeMap.keySet()) {
            XNode node = nodeMap.get(repoID);
            idMap.put(node.getAttributeValue("id"), repoID);
        }
        return idMap;
    }


    private String getNetLayoutXML(YNet net) {
        YLayout layout = new LayoutExporter().parse();
        YNetLayout netLayout = layout.getNetLayout(net.getID());
        return netLayout.toXML();
    }

}
