//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.05.22 at 10:45:47 AM EST 
//


package org.yawlfoundation.sb.camerainfo;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for camInfoSumType_3 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="camInfoSumType_3">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="totalFTGE_prevDrawn" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="footageDRN_today" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="previouslyExposed" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="exposedToday" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "camInfoSumType_3", propOrder = {
    "totalFTGEPrevDrawn",
    "footageDRNToday",
    "previouslyExposed",
    "exposedToday"
})
public class CamInfoSumType3 {

    @XmlElement(name = "totalFTGE_prevDrawn", required = true)
    protected BigInteger totalFTGEPrevDrawn;
    @XmlElement(name = "footageDRN_today", required = true)
    protected BigInteger footageDRNToday;
    @XmlElement(required = true)
    protected BigInteger previouslyExposed;
    @XmlElement(required = true)
    protected BigInteger exposedToday;

    /**
     * Gets the value of the totalFTGEPrevDrawn property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTotalFTGEPrevDrawn() {
        return totalFTGEPrevDrawn;
    }

    /**
     * Sets the value of the totalFTGEPrevDrawn property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTotalFTGEPrevDrawn(BigInteger value) {
        this.totalFTGEPrevDrawn = value;
    }

    /**
     * Gets the value of the footageDRNToday property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFootageDRNToday() {
        return footageDRNToday;
    }

    /**
     * Sets the value of the footageDRNToday property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFootageDRNToday(BigInteger value) {
        this.footageDRNToday = value;
    }

    /**
     * Gets the value of the previouslyExposed property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPreviouslyExposed() {
        return previouslyExposed;
    }

    /**
     * Sets the value of the previouslyExposed property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPreviouslyExposed(BigInteger value) {
        this.previouslyExposed = value;
    }

    /**
     * Gets the value of the exposedToday property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getExposedToday() {
        return exposedToday;
    }

    /**
     * Sets the value of the exposedToday property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setExposedToday(BigInteger value) {
        this.exposedToday = value;
    }

}
