//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.05.22 at 10:45:47 AM EST 
//


package org.yawlfoundation.sb.camerainfo;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for takeInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="takeInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="take" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="counter" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="length" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="print" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="printSetting" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="essentialInfo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "takeInfoType", propOrder = {
    "take",
    "counter",
    "length",
    "print",
    "printSetting",
    "essentialInfo"
})
public class TakeInfoType {

    @XmlElement(required = true)
    protected BigInteger take;
    @XmlElement(required = true)
    protected BigInteger counter;
    @XmlElement(required = true)
    protected BigInteger length;
    protected boolean print;
    @XmlElement(required = true)
    protected String printSetting;
    @XmlElement(required = true)
    protected String essentialInfo;

    /**
     * Gets the value of the take property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTake() {
        return take;
    }

    /**
     * Sets the value of the take property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTake(BigInteger value) {
        this.take = value;
    }

    /**
     * Gets the value of the counter property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCounter() {
        return counter;
    }

    /**
     * Sets the value of the counter property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCounter(BigInteger value) {
        this.counter = value;
    }

    /**
     * Gets the value of the length property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLength() {
        return length;
    }

    /**
     * Sets the value of the length property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLength(BigInteger value) {
        this.length = value;
    }

    /**
     * Gets the value of the print property.
     * 
     */
    public boolean isPrint() {
        return print;
    }

    /**
     * Sets the value of the print property.
     * 
     */
    public void setPrint(boolean value) {
        this.print = value;
    }

    /**
     * Gets the value of the printSetting property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrintSetting() {
        return printSetting;
    }

    /**
     * Sets the value of the printSetting property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrintSetting(String value) {
        this.printSetting = value;
    }

    /**
     * Gets the value of the essentialInfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEssentialInfo() {
        return essentialInfo;
    }

    /**
     * Sets the value of the essentialInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEssentialInfo(String value) {
        this.essentialInfo = value;
    }

}
