package com.nexusbpm.editor;

import java.io.File;
import java.util.Set;

import javax.swing.JFrame;
import javax.swing.JSplitPane;
import javax.swing.UIManager;

import org.apache.log4j.PropertyConfigurator;

import au.edu.qut.yawl.elements.YNet;
import au.edu.qut.yawl.elements.YSpecification;
import au.edu.qut.yawl.persistence.dao.DAOFactory;
import au.edu.qut.yawl.persistence.dao.SpecificationDAO;
import au.edu.qut.yawl.persistence.managed.DataContext;
import au.edu.qut.yawl.persistence.managed.DataProxy;

import com.nexusbpm.command.Command;
import com.nexusbpm.command.CommandExecutor;
import com.nexusbpm.command.CreateConditionCommand;
import com.nexusbpm.command.CreateFlowCommand;
import com.nexusbpm.command.CreateNetCommand;
import com.nexusbpm.command.CreateNexusComponent;
import com.nexusbpm.command.CreateSpecificationCommand;
import com.nexusbpm.editor.desktop.DesktopPane;
import com.nexusbpm.editor.icon.ApplicationIcon;
import com.nexusbpm.editor.logger.CapselaLogPanel;
import com.nexusbpm.editor.persistence.EditorDataProxy;
import com.nexusbpm.editor.tree.DatasourceRoot;
import com.nexusbpm.editor.tree.STree;
import com.nexusbpm.editor.tree.SharedNode;
import com.nexusbpm.editor.tree.SharedNodeTreeModel;
import com.nexusbpm.services.NexusServiceInfo;

/**
 *
 * @author  SandozM
 */
public class WorkflowEditor extends javax.swing.JFrame {
    
	private final static int DEFAULT_CLIENT_WIDTH = 800;
	private final static int DEFAULT_CLIENT_HEIGHT = 692;
	private final static int DEFAULT_COMMAND_STACK_SIZE = 20;
	private static CommandExecutor executor = new CommandExecutor(DEFAULT_COMMAND_STACK_SIZE);
	private static WorkflowEditor singleton = null;
	
    /**
     * Creates new form WorkflowEditor 
     */
    private WorkflowEditor() {
		PropertyConfigurator.configure( WorkflowEditor.class.getResource( "client.logging.properties" ) );
    	initComponents();
        this.pack();
    	this.setSize(DEFAULT_CLIENT_WIDTH,DEFAULT_CLIENT_HEIGHT);
    }
    
    public static WorkflowEditor getInstance() {
    	if (WorkflowEditor.singleton == null) {
    		WorkflowEditor.singleton = new WorkflowEditor();
    	}
    	return singleton;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">                          

    
    private void initComponents() {
	    JFrame.setDefaultLookAndFeelDecorated(true);
		try {
	        UIManager.setLookAndFeel(
	            UIManager.getSystemLookAndFeelClassName());
	    } catch (Exception e) { e.printStackTrace();}
        componentEditorSplitPane = new javax.swing.JSplitPane();
        componentList1Panel = new javax.swing.JPanel();
        componentList2Panel = new javax.swing.JPanel();
        componentTreesSplitPane = new JSplitPane();
        componentTreesPanel = new javax.swing.JPanel();
        componentList1ScrollPane = new javax.swing.JScrollPane();
        componentList2ScrollPane = new javax.swing.JScrollPane();
        SpecificationDAO memdao = DAOFactory.getDAOFactory(DAOFactory.Type.MEMORY).getSpecificationModelDAO();
        SpecificationDAO filedao = DAOFactory.getDAOFactory(DAOFactory.Type.FILE).getSpecificationModelDAO();
//        SpecificationDAO hibernatedao = DAOFactory.getDAOFactory(DAOFactory.Type.HIBERNATE).getSpecificationModelDAO();

        DataContext memdc = new DataContext(memdao, EditorDataProxy.class);
        DataContext filedc = new DataContext(filedao, EditorDataProxy.class);
//        DataContext hibdc = new DataContext(hibernatedao, EditorDataProxy.class);
        
        Object o = new DatasourceRoot("virtual://memory/home/sandozm/templates/");
        EditorDataProxy memdp = (EditorDataProxy) memdc.createProxy(o, null);
        memdc.attachProxy(memdp, o);
        
        try {
        	Command createSpec = new CreateSpecificationCommand( memdp, "testspec" );
        	executor.executeCommand(createSpec).get();
            Set<DataProxy> children = memdc.getChildren( memdp, false );
            for( DataProxy child : children ) {
                if( child.getData() instanceof YSpecification ) {
                    Command createNet = new CreateNetCommand( (EditorDataProxy) child, "testnet" );
                    executor.executeCommand(createNet).get();
                    Set<DataProxy> subchildren = child.getContext().getChildren( child, false );
                    for( DataProxy subchild : subchildren ) {
                        if( subchild.getData() instanceof YNet ) {
                            Command command = new CreateConditionCommand( (EditorDataProxy) subchild,
                                    CreateConditionCommand.TYPE_INPUT_CONDITION, null);
                            executor.executeCommand(command).get();
                            command = new CreateConditionCommand( (EditorDataProxy) subchild,
                                    CreateConditionCommand.TYPE_OUTPUT_CONDITION, null);
                            executor.executeCommand(command).get();
                            command = new CreateNexusComponent( (EditorDataProxy) subchild,
                                    "jython", "jython", NexusServiceInfo.getServiceWithName( "Jython" ) );
                            executor.executeCommand(command).get();
                            command = new CreateNexusComponent( (EditorDataProxy) subchild,
                                    "email sender", "email_sender", NexusServiceInfo.getServiceWithName( "EmailSender" ) );
                            executor.executeCommand(command).get();
                            YNet net = (YNet) subchild.getData();
                            command = new CreateFlowCommand(
                                    (EditorDataProxy) memdc.getDataProxy( net.getInputCondition(), null ),
                                    (EditorDataProxy) memdc.getDataProxy( net.getNetElement( "jython" ), null ) );
                            executor.executeCommand(command).get();
                            command = new CreateFlowCommand(
                                    (EditorDataProxy) memdc.getDataProxy( net.getNetElement( "jython" ), null ),
                                    (EditorDataProxy) memdc.getDataProxy( net.getNetElement( "email_sender" ), null ) );
                            executor.executeCommand(command).get();
                            command = new CreateFlowCommand(
                                    (EditorDataProxy) memdc.getDataProxy( net.getNetElement( "email_sender" ), null ),
                                    (EditorDataProxy) memdc.getDataProxy( net.getOutputCondition(), null ) );
                            executor.executeCommand(command).get();
                        }
                    }
                }
            }
        }
        catch( Exception e ) {
            e.printStackTrace( System.out );
            System.out.flush();
        }
        
        String dataroot = new File("exampleSpecs/").toURI().toString();
        o = new DatasourceRoot(dataroot);
        EditorDataProxy filedp = (EditorDataProxy) filedc.createProxy(o, null);
        filedc.attachProxy(filedp, o);

//        EditorDataProxy hibdp = (EditorDataProxy) hibdc.getDataProxy(new DatasourceRoot("hibernate://home/sandozm/"), null);
        
        SharedNode memRootNode = new SharedNode(memdp);
        SharedNode fileRootNode = new SharedNode(filedp);
//        SharedNode hibernateRootNode = new SharedNode(hibdp);

        SharedNodeTreeModel memTreeModel = new SharedNodeTreeModel(memRootNode);
        SharedNodeTreeModel fileTreeModel = new SharedNodeTreeModel(fileRootNode);
//        SharedNodeTreeModel hibernateTreeModel = new SharedNodeTreeModel(hibernateRootNode);

        memRootNode.setTreeModel(memTreeModel);
        fileRootNode.setTreeModel(fileTreeModel);
//        hibernateRootNode.setTreeModel(hibernateTreeModel);
        
        memoryComponentListTree = new STree(memTreeModel, componentList1ScrollPane);
        memoryComponentListTree.setShowsRootHandles(false);
        memoryComponentListTree.setRootVisible(true);
        memoryComponentListTree.setRowHeight(34);
        
        fileComponentListTree = new STree(fileTreeModel, componentList1ScrollPane);
        fileComponentListTree.setShowsRootHandles(false);
        fileComponentListTree.setRootVisible(true);
        fileComponentListTree.setRowHeight(34);
        
        desktopAndStatusPanel = new javax.swing.JPanel();
        desktopLogSplitPane = new javax.swing.JSplitPane();
        desktopPanel = new javax.swing.JPanel();
        desktopScrollPane = new javax.swing.JScrollPane();
        desktopPane = new DesktopPane();
        logPanel = new CapselaLogPanel();
        logTextScrollPane = new javax.swing.JScrollPane();
        logTextArea = new javax.swing.JTextArea();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentsMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Nexus/BPM Process Editor");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.lightGray);
        setName("Nexus/BPM Process Editor");
        this.setIconImage(ApplicationIcon.getIcon("NexusFrame.window_icon", ApplicationIcon.LARGE_SIZE).getImage());
        componentEditorSplitPane.setDividerLocation(200);
        componentList1Panel.setLayout(new java.awt.BorderLayout());
        componentList2Panel.setLayout(new java.awt.BorderLayout());
        componentTreesPanel.setLayout(new java.awt.BorderLayout());

        componentList1ScrollPane.setViewportView(memoryComponentListTree);

        componentList2ScrollPane.setViewportView(fileComponentListTree);

        componentList1Panel.add(componentList1ScrollPane, java.awt.BorderLayout.CENTER);
        componentList2Panel.add(componentList2ScrollPane, java.awt.BorderLayout.CENTER);

        componentEditorSplitPane.setLeftComponent(componentTreesPanel);
        componentTreesSplitPane.setDividerLocation(300);
        componentTreesSplitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        componentTreesSplitPane.setTopComponent(componentList1Panel);
        componentTreesSplitPane.setBottomComponent(componentList2Panel);
        componentTreesPanel.add(componentTreesSplitPane);

        desktopAndStatusPanel.setLayout(new java.awt.GridLayout(1, 0));

        desktopLogSplitPane.setDividerLocation(480);
        desktopLogSplitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        desktopLogSplitPane.setRequestFocusEnabled(false);
        desktopPanel.setLayout(new java.awt.GridLayout(1, 0));

        desktopPane.setBackground(new java.awt.Color(135, 145, 161));
        desktopScrollPane.setViewportView(desktopPane);

        desktopPanel.add(desktopScrollPane);

        desktopLogSplitPane.setTopComponent(desktopPanel);

        desktopLogSplitPane.setBottomComponent(logPanel);

        desktopAndStatusPanel.add(desktopLogSplitPane);

        componentEditorSplitPane.setRightComponent(desktopAndStatusPanel);

        getContentPane().add(componentEditorSplitPane, java.awt.BorderLayout.CENTER);

        fileMenu.setText("File");
        openMenuItem.setText("Open");
        fileMenu.add(openMenuItem);

        saveMenuItem.setText("Save");
        fileMenu.add(saveMenuItem);

        saveAsMenuItem.setText("Save As ...");
        fileMenu.add(saveAsMenuItem);

        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });

        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setText("Edit");
        cutMenuItem.setText("Cut");
        editMenu.add(cutMenuItem);

        copyMenuItem.setText("Copy");
        editMenu.add(copyMenuItem);

        pasteMenuItem.setText("Paste");
        editMenu.add(pasteMenuItem);

        deleteMenuItem.setText("Delete");
        editMenu.add(deleteMenuItem);

        menuBar.add(editMenu);

        helpMenu.setText("Help");
        contentsMenuItem.setText("Contents");
        helpMenu.add(contentsMenuItem);

        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        pack();
    }
    // </editor-fold>                        

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {                                             
        System.exit(0);
    }                                            
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
    public void run() {
                WorkflowEditor.getInstance().setVisible(true);
            }
        });
    }
    
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JSplitPane componentEditorSplitPane;
    private javax.swing.JPanel componentList1Panel;
    private javax.swing.JPanel componentList2Panel;
    private javax.swing.JSplitPane componentTreesSplitPane;
    private javax.swing.JPanel componentTreesPanel;
    private javax.swing.JScrollPane componentList1ScrollPane;
    private javax.swing.JScrollPane componentList2ScrollPane;
    private STree memoryComponentListTree;
    private STree fileComponentListTree;
    private javax.swing.JMenuItem contentsMenuItem;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JPanel desktopAndStatusPanel;
    private javax.swing.JSplitPane desktopLogSplitPane;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JPanel desktopPanel;
    private javax.swing.JScrollPane desktopScrollPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private CapselaLogPanel logPanel;
    private javax.swing.JTextArea logTextArea;
    private javax.swing.JScrollPane logTextScrollPane;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem pasteMenuItem;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveMenuItem;

	public javax.swing.JDesktopPane getDesktopPane() {
		return desktopPane;
	}

	public static CommandExecutor getExecutor() {
		return executor;
	}

	public static void setExecutor(CommandExecutor executor) {
		WorkflowEditor.executor = executor;
	}

}
