package com.nexusbpm.editor;

import javax.swing.JFrame;
import javax.swing.JSplitPane;
import javax.swing.UIManager;

import au.edu.qut.yawl.elements.YSpecification;
import au.edu.qut.yawl.persistence.dao.DAOFactory;
import au.edu.qut.yawl.persistence.dao.SpecificationDAO;
import au.edu.qut.yawl.persistence.managed.DataContext;

import com.nexusbpm.editor.desktop.DesktopPane;
import com.nexusbpm.editor.icon.ApplicationIcon;
import com.nexusbpm.editor.logger.CapselaLogPanel;
import com.nexusbpm.editor.persistence.EditorDataProxy;
import com.nexusbpm.editor.tree.DatasourceRoot;
import com.nexusbpm.editor.tree.STree;
import com.nexusbpm.editor.tree.SharedNode;
import com.nexusbpm.editor.tree.SharedNodeTreeModel;

/**
 *
 * @author  SandozM
 */
public class WorkflowEditor extends javax.swing.JFrame {
    
	private final static int DEFAULT_CLIENT_WIDTH = 800;
	private final static int DEFAULT_CLIENT_HEIGHT = 692;

	private static WorkflowEditor singleton = null;
	
    /**
     * Creates new form WorkflowEditor 
     */
    private WorkflowEditor() {
        initComponents();
        this.pack();
    	this.setSize(DEFAULT_CLIENT_WIDTH,DEFAULT_CLIENT_HEIGHT);
    }
    
    public static WorkflowEditor getInstance() {
    	if (WorkflowEditor.singleton == null) {
    		WorkflowEditor.singleton = new WorkflowEditor();
    	}
    	return singleton;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">                          
    private void initComponents() {
	    JFrame.setDefaultLookAndFeelDecorated(true);
		try {
	        UIManager.setLookAndFeel(
	            UIManager.getSystemLookAndFeelClassName());
	    } catch (Exception e) { e.printStackTrace();}
        componentEditorSplitPane = new javax.swing.JSplitPane();
        componentList1Panel = new javax.swing.JPanel();
        componentList2Panel = new javax.swing.JPanel();
        componentTreesSplitPane = new JSplitPane();
        componentTreesPanel = new javax.swing.JPanel();
        componentList1ScrollPane = new javax.swing.JScrollPane();
        componentList2ScrollPane = new javax.swing.JScrollPane();
        SpecificationDAO dao1 = DAOFactory.getDAOFactory(DAOFactory.Type.MEMORY).getSpecificationModelDAO();
        SpecificationDAO dao2 = DAOFactory.getDAOFactory(DAOFactory.Type.FILE).getSpecificationModelDAO();
        DataContext dc1 = new DataContext(dao1, EditorDataProxy.class);
        DataContext dc2 = new DataContext(dao2, EditorDataProxy.class);
        EditorDataProxy dp1 = (EditorDataProxy) dc1.getDataProxy(new DatasourceRoot("/home/sandozm/templates/testing/"), null);
//        EditorDataProxy dp1 = (EditorDataProxy) dc1.getDataProxy(new DatasourceRoot("/home/sandozm/"), null);
        EditorDataProxy dp2 = (EditorDataProxy) dc2.getDataProxy(new DatasourceRoot("./exampleSpecs/xml/"), null);

        
        EditorDataProxy dprox = (EditorDataProxy) dc1.getChildren(dp1).toArray()[0];
        YSpecification spec = (YSpecification) dprox.getData();
        spec.setID("C:\\temp\\TEST.xml");
        dc2.put(dprox);
        SharedNode root1 = new SharedNode(dp1);
        SharedNode root2 = new SharedNode(dp2);
        SharedNodeTreeModel treeModel1 = new SharedNodeTreeModel(root1);
        SharedNodeTreeModel treeModel2 = new SharedNodeTreeModel(root2);
        root1.setTreeModel(treeModel1);
        root2.setTreeModel(treeModel2);
        componentList1Tree = new STree(treeModel1, componentList1ScrollPane);
        componentList1Tree.setShowsRootHandles(false);
        componentList1Tree.setRootVisible(true);
        componentList1Tree.setRowHeight(25);
        
        componentList2Tree = new STree(treeModel2, componentList1ScrollPane);
        componentList2Tree.setShowsRootHandles(false);
        componentList2Tree.setRootVisible(true);
        componentList2Tree.setRowHeight(25);
        
        desktopAndStatusPanel = new javax.swing.JPanel();
        desktopLogSplitPane = new javax.swing.JSplitPane();
        desktopPanel = new javax.swing.JPanel();
        desktopScrollPane = new javax.swing.JScrollPane();
        desktopPane = new DesktopPane();
        logPanel = new CapselaLogPanel();
        logTextScrollPane = new javax.swing.JScrollPane();
        logTextArea = new javax.swing.JTextArea();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentsMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("NexusBPM Process Editor");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.lightGray);
        setName("NexusBPM Process Editor");
        this.setIconImage(ApplicationIcon.getIcon("NexusFrame.window_icon", ApplicationIcon.MEDIUM_SIZE).getImage());
        componentEditorSplitPane.setDividerLocation(200);
        componentList1Panel.setLayout(new java.awt.BorderLayout());
        componentList2Panel.setLayout(new java.awt.BorderLayout());
        componentTreesPanel.setLayout(new java.awt.BorderLayout());

        componentList1ScrollPane.setViewportView(componentList1Tree);

        componentList2ScrollPane.setViewportView(componentList2Tree);

        componentList1Panel.add(componentList1ScrollPane, java.awt.BorderLayout.CENTER);
        componentList2Panel.add(componentList2ScrollPane, java.awt.BorderLayout.CENTER);

        componentEditorSplitPane.setLeftComponent(componentTreesPanel);
        componentTreesSplitPane.setDividerLocation(300);
        componentTreesSplitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        componentTreesSplitPane.setTopComponent(componentList1Panel);
        componentTreesSplitPane.setBottomComponent(componentList2Panel);
        componentTreesPanel.add(componentTreesSplitPane);

        desktopAndStatusPanel.setLayout(new java.awt.GridLayout(1, 0));

        desktopLogSplitPane.setDividerLocation(480);
        desktopLogSplitPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        desktopLogSplitPane.setRequestFocusEnabled(false);
        desktopPanel.setLayout(new java.awt.GridLayout(1, 0));

        desktopPane.setBackground(new java.awt.Color(135, 145, 161));
        desktopScrollPane.setViewportView(desktopPane);

        desktopPanel.add(desktopScrollPane);

        desktopLogSplitPane.setTopComponent(desktopPanel);

        desktopLogSplitPane.setBottomComponent(logPanel);

        desktopAndStatusPanel.add(desktopLogSplitPane);

        componentEditorSplitPane.setRightComponent(desktopAndStatusPanel);

        getContentPane().add(componentEditorSplitPane, java.awt.BorderLayout.CENTER);

        fileMenu.setText("File");
        openMenuItem.setText("Open");
        fileMenu.add(openMenuItem);

        saveMenuItem.setText("Save");
        fileMenu.add(saveMenuItem);

        saveAsMenuItem.setText("Save As ...");
        fileMenu.add(saveAsMenuItem);

        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });

        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setText("Edit");
        cutMenuItem.setText("Cut");
        editMenu.add(cutMenuItem);

        copyMenuItem.setText("Copy");
        editMenu.add(copyMenuItem);

        pasteMenuItem.setText("Paste");
        editMenu.add(pasteMenuItem);

        deleteMenuItem.setText("Delete");
        editMenu.add(deleteMenuItem);

        menuBar.add(editMenu);

        helpMenu.setText("Help");
        contentsMenuItem.setText("Contents");
        helpMenu.add(contentsMenuItem);

        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        pack();
    }
    // </editor-fold>                        

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {                                             
        System.exit(0);
    }                                            
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
    public void run() {
                new WorkflowEditor().setVisible(true);
            }
        });
    }
    
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JSplitPane componentEditorSplitPane;
    private javax.swing.JPanel componentList1Panel;
    private javax.swing.JPanel componentList2Panel;
    private javax.swing.JSplitPane componentTreesSplitPane;
    private javax.swing.JPanel componentTreesPanel;
    private javax.swing.JScrollPane componentList1ScrollPane;
    private javax.swing.JScrollPane componentList2ScrollPane;
    private javax.swing.JTree componentList1Tree;
    private javax.swing.JTree componentList2Tree;
    private javax.swing.JMenuItem contentsMenuItem;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JPanel desktopAndStatusPanel;
    private javax.swing.JSplitPane desktopLogSplitPane;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JPanel desktopPanel;
    private javax.swing.JScrollPane desktopScrollPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private CapselaLogPanel logPanel;
    private javax.swing.JTextArea logTextArea;
    private javax.swing.JScrollPane logTextScrollPane;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem pasteMenuItem;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
}
